# Service Health Check Monitoring Configuration
# Comprehensive monitoring for all AIWFE services

# Core Services
- job_name: 'api-health'
  static_configs:
    - targets: ['api:8000']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

- job_name: 'worker-health'
  static_configs:
    - targets: ['worker:8001']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

# Cognitive Services
- job_name: 'perception-service-health'
  static_configs:
    - targets: ['perception-service:8001']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

- job_name: 'memory-service-health'
  static_configs:
    - targets: ['memory-service:8002']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

- job_name: 'reasoning-service-health'
  static_configs:
    - targets: ['reasoning-service:8003']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

- job_name: 'coordination-service-health'
  static_configs:
    - targets: ['coordination-service:8004']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

- job_name: 'learning-service-health'
  static_configs:
    - targets: ['learning-service:8005']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

# Infrastructure Services
- job_name: 'infrastructure-recovery-health'
  static_configs:
    - targets: ['infrastructure-recovery-service:8010']
  metrics_path: '/health'
  scrape_interval: 30s
  scrape_timeout: 10s

# Database Services
- job_name: 'postgres-health'
  static_configs:
    - targets: ['postgres:5432']
  metrics_path: '/metrics'
  scrape_interval: 30s

- job_name: 'pgbouncer-health'
  static_configs:
    - targets: ['pgbouncer:6432']
  metrics_path: '/metrics'
  scrape_interval: 30s

# Cache Services
- job_name: 'redis-health'
  static_configs:
    - targets: ['redis:6379']
  metrics_path: '/metrics'
  scrape_interval: 30s

# Vector Database
- job_name: 'qdrant-health'
  static_configs:
    - targets: ['qdrant:6333']
  metrics_path: '/metrics'
  scrape_interval: 30s

# Reverse Proxy Services
- job_name: 'caddy-health'
  static_configs:
    - targets: ['caddy_reverse_proxy:80', 'caddy_reverse_proxy:443']
  metrics_path: '/metrics'
  scrape_interval: 30s

# Model Services
- job_name: 'ollama-health'
  static_configs:
    - targets: ['ollama:11434']
  metrics_path: '/api/health'
  scrape_interval: 60s

# Alert Rules for Health Checks
alert_rules:
  - name: service_health
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"
      
      - alert: ServiceDegraded
        expr: health_status == "degraded"
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Service {{ $labels.job }} is degraded"
          description: "{{ $labels.job }} has been in degraded state for more than 5 minutes"
      
      - alert: ImportError
        expr: import_errors > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Import errors in {{ $labels.job }}"
          description: "{{ $labels.job }} is experiencing import errors - check PYTHONPATH configuration"