"""
Makes the SQLAlchemy models available for import from the package level.

Example: from shared.database.models import User, Document
"""
from ._models import (
    Base,
    User,
    UserRole,
    UserStatus,
    UserProfile,
    Document,
    DocumentStatus,
    DocumentChunk,
    ChatHistory,
    ChatSessionSummary,
    ChatMessage,
    SessionState,
    Calendar,
    Event,
    EventCategory,
    CategoryWeight,
    TimeBudget,
    TaskStatus,
    TaskPriority,
    TaskType,
    Project,
    Task,
    UserCategory,
    MissionInterview,
    SemanticInsight,
    CodeTemplate,
    AIAnalysisHistory,
    UserOAuthToken,
    GoogleService,
    TaskFeedback,
    SystemSetting,
    MessageFeedback,
    UserHistorySummary,
    SystemPrompt,
)
from .auth_models import (
    DeviceSecurityLevel,
    TwoFactorMethod,
    DeviceType,
    RegisteredDevice,
    UserTwoFactorAuth,
    PasskeyCredential,
    TwoFactorChallenge,
    DeviceLoginAttempt,
)
from .access_request import AccessRequest
from .agent_config_models import (
    LLMProvider,
    AgentType,
    GPUAssignmentStrategy,
    ModelLoadStrategy,
    LegacyAgentConfiguration,
    LegacyAgentMetrics,
    LegacyGPUResourceAllocation,
    LegacyModelInstance,
)
from .enhanced_2fa_models import (
    TwoFactorPolicyType,
    TwoFactorGraceStatus,
    SMSProvider,
    EmailProvider,
    TwoFactorAuditAction,
    TwoFactorPolicy,
    UserTwoFactorGracePeriod,
    UserSMSTwoFactor,
    UserEmailTwoFactor,
    TwoFactorAuditLog,
    TwoFactorVerificationCode,
    TwoFactorAdminOverride,
    TwoFactorComplianceReport,
    UserTwoFactorSettings,
)
from .unified_memory_models import (
    ChatModeSession,
    RouterDecisionLog,
    SimpleChatContext,
    # UnifiedMemoryVector,  # TEMPORARILY REMOVED: metadata conflict
    CrossServiceMemorySync,
)
from .security_models import (
    AuditOperation,
    ViolationSeverity,
    AccessLevel,
    RetentionPolicyType,
    SecurityTier,
    SecurityRequirementType,
    SecurityRequirementStatus,
    SecurityActionType,
    SecurityActionStatus,
    AuditLog,
    SecurityViolation,
    DataAccessLog,
    DataRetentionPolicy,
    QdrantAccessControl,
    EncryptedField,
    SecurityMetric,
    PrivacyRequest,
    CrossServiceAuth,
    SecurityAction,
    UserSecurityTier,
    SecurityRequirement,
    SecurityTierPolicy,
    CertificateRequest,
    SecurityTierUpgradeLog,
)
from .enterprise_audit_models import (
    ComplianceStandard,
    AuditEventCategory,
    AuditEventSeverity,
    ComplianceStatus,
    ThreatType,
    EnterpriseAuditEvent,
    ThreatIntelligenceEvent,
    ComplianceAssessment,
    ForensicInvestigation,
    DataRetentionLog,
)
# Import the active AgentConfiguration from Helios Multi-Agent framework
# TEMPORARILY DISABLED: Tables don't exist yet due to incomplete migration
# from .helios_multi_agent_models import (
#     AgentConfiguration,
#     AgentProfile,
#     GPUResource,
#     GPUAllocation,
#     TaskDelegation,
#     AgentResponse,
#     TaskSynthesis,
#     MultiAgentConversation,
#     AgentParticipation,
#     LoadBalancingRule,
#     ResourceConstraint,
#     AgentStatus,
#     TaskDelegationStatus,
#     ConversationPhase,
#     GPUAllocationStatus,
#     ModelProvider,
# )

__all__ = [
    "Base",
    "User",
    "UserRole",
    "UserStatus",
    "UserProfile",
    "Document",
    "DocumentStatus",
    "DocumentChunk",
    "ChatHistory",
    "ChatSessionSummary",
    "ChatMessage",
    "SessionState",
    "Calendar",
    "Event",
    "EventCategory",
    "CategoryWeight",
    "TimeBudget",
    "TaskStatus",
    "TaskPriority",
    "TaskType",
    "Project",
    "Task",
    "UserCategory",
    "MissionInterview",
    "SemanticInsight",
    "CodeTemplate",
    "AIAnalysisHistory",
    "UserOAuthToken",
    "GoogleService",
    "TaskFeedback",
    "SystemSetting",
    "MessageFeedback",
    "UserHistorySummary",
    "SystemPrompt",
    # 2FA and device management models
    "DeviceSecurityLevel",
    "TwoFactorMethod",
    "DeviceType",
    "RegisteredDevice",
    "UserTwoFactorAuth",
    "PasskeyCredential",
    "TwoFactorChallenge",
    "DeviceLoginAttempt",
    "AccessRequest",
    # Enhanced 2FA models
    "TwoFactorPolicyType",
    "TwoFactorGraceStatus",
    "SMSProvider",
    "EmailProvider",
    "TwoFactorAuditAction",
    "TwoFactorPolicy",
    "UserTwoFactorGracePeriod",
    "UserSMSTwoFactor",
    "UserEmailTwoFactor",
    "TwoFactorAuditLog",
    "TwoFactorVerificationCode",
    "TwoFactorAdminOverride",
    "TwoFactorComplianceReport",
    "UserTwoFactorSettings",
    # Legacy Agent Configuration models
    "LLMProvider",
    "AgentType", 
    "GPUAssignmentStrategy",
    "ModelLoadStrategy",
    "LegacyAgentConfiguration",
    "LegacyAgentMetrics",
    "LegacyGPUResourceAllocation",
    "LegacyModelInstance",
    # Unified Memory Store models
    "ChatModeSession",
    "RouterDecisionLog",
    "SimpleChatContext",
    # "UnifiedMemoryVector",  # TEMPORARILY REMOVED: metadata conflict
    "CrossServiceMemorySync",
    # Security models
    "AuditOperation",
    "ViolationSeverity",
    "AccessLevel",
    "RetentionPolicyType",
    "SecurityTier",
    "SecurityRequirementType",
    "SecurityRequirementStatus",
    "SecurityActionType",
    "SecurityActionStatus",
    "AuditLog",
    "SecurityViolation",
    "DataAccessLog",
    "DataRetentionPolicy",
    "QdrantAccessControl",
    "EncryptedField",
    "SecurityMetric",
    "PrivacyRequest",
    "CrossServiceAuth",
    "SecurityAction",
    "UserSecurityTier",
    "SecurityRequirement",
    "SecurityTierPolicy",
    "CertificateRequest",
    "SecurityTierUpgradeLog",
    # Enterprise audit models
    "ComplianceStandard",
    "AuditEventCategory",
    "AuditEventSeverity",
    "ComplianceStatus",
    "ThreatType",
    "EnterpriseAuditEvent",
    "ThreatIntelligenceEvent",
    "ComplianceAssessment",
    "ForensicInvestigation",
    "DataRetentionLog",
    # Active Helios Multi-Agent models - TEMPORARILY DISABLED
    # "AgentConfiguration",
    # "AgentProfile",
    # "GPUResource", 
    # "GPUAllocation",
    # "TaskDelegation",
    # "AgentResponse",
    # "TaskSynthesis",
    # "MultiAgentConversation",
    # "AgentParticipation",
    # "LoadBalancingRule",
    # "ResourceConstraint",
    # "AgentStatus",
    # "TaskDelegationStatus",
    # "ConversationPhase",
    # "GPUAllocationStatus",
    # "ModelProvider",
]

