groups:
  - name: authentication_security_alerts
    rules:
      # Circuit Breaker Alerts
      - alert: CircuitBreakerOpen
        expr: circuit_breaker_state{service="authentication"} == 2
        for: 1m
        labels:
          severity: critical
          service: authentication
          category: security
        annotations:
          summary: "Authentication circuit breaker is OPEN"
          description: "The authentication circuit breaker for {{ $labels.service }} has been in OPEN state for more than 1 minute. This indicates repeated authentication failures and service degradation."
          runbook_url: "https://docs.aiwfe.com/runbooks/authentication-circuit-breaker"

      - alert: HighAuthenticationFailureRate
        expr: (rate(circuit_breaker_failures_total{service="authentication"}[5m]) / rate(circuit_breaker_requests_total{service="authentication"}[5m])) * 100 > 10
        for: 2m
        labels:
          severity: warning
          service: authentication
          category: security
        annotations:
          summary: "High authentication failure rate detected"
          description: "Authentication failure rate is {{ $value }}% over the last 5 minutes, exceeding the 10% threshold."
          
      - alert: AuthenticationLoopDetected
        expr: rate(circuit_breaker_loop_prevention_total{service="authentication"}[1m]) > 1
        for: 30s
        labels:
          severity: critical
          service: authentication
          category: security
        annotations:
          summary: "Authentication loop prevention triggered"
          description: "Authentication loop prevention has been triggered {{ $value }} times in the last minute, indicating potential authentication flooding or loops."

      # Redis Security Alerts  
      - alert: RedisConnectionFailure
        expr: redis_connection_health{instance="ai_workflow_engine-redis-1"} == 0
        for: 30s
        labels:
          severity: critical
          service: redis
          category: infrastructure
        annotations:
          summary: "Redis connection health check failed"
          description: "Redis connection health check has been failing for more than 30 seconds. This may impact authentication caching and session management."

      - alert: RedisCircuitBreakerOpen
        expr: circuit_breaker_state{service="redis"} == 2
        for: 2m
        labels:
          severity: warning
          service: redis
          category: infrastructure
        annotations:
          summary: "Redis circuit breaker is OPEN"
          description: "The Redis circuit breaker has been OPEN for more than 2 minutes, indicating persistent Redis connectivity issues."

      # Security Threat Detection
      - alert: BruteForceAttackDetected
        expr: rate(security_events_total{event_type="brute_force",severity="high"}[1m]) > 0
        for: 0s
        labels:
          severity: critical
          category: security
          attack_type: brute_force
        annotations:
          summary: "Brute force attack detected"
          description: "A brute force attack has been detected. Multiple authentication failures from the same source IP within a short time window."

      - alert: PathTraversalAttempt
        expr: rate(security_events_total{event_type="path_traversal",severity="high"}[1m]) > 0
        for: 0s
        labels:
          severity: critical
          category: security
          attack_type: path_traversal
        annotations:
          summary: "Path traversal attack attempt detected"
          description: "A path traversal attack attempt has been detected. Suspicious paths containing directory traversal patterns were accessed."

      - alert: RateLimitExceeded
        expr: rate(security_events_total{event_type="rate_limit_exceeded",severity="medium"}[5m]) > 2
        for: 1m
        labels:
          severity: warning
          category: security
          attack_type: rate_limit
        annotations:
          summary: "Rate limit exceeded multiple times"
          description: "Rate limits have been exceeded {{ $value }} times in the last 5 minutes, indicating potential DoS attempts."

      # Authentication Performance Alerts
      - alert: SlowCircuitBreakerRecovery
        expr: circuit_breaker_recovery_time_seconds{service="authentication"} > 30
        for: 1m
        labels:
          severity: warning
          service: authentication
          category: performance
        annotations:
          summary: "Slow circuit breaker recovery time"
          description: "Circuit breaker recovery time is {{ $value }} seconds, exceeding the 30-second threshold."

      - alert: HighAuthenticationLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{endpoint=~".*auth.*"}[5m])) > 0.5
        for: 3m
        labels:
          severity: warning
          service: authentication
          category: performance
        annotations:
          summary: "High authentication latency detected"
          description: "95th percentile authentication latency is {{ $value }}s, exceeding 500ms threshold for more than 3 minutes."

      # WebSocket Security
      - alert: HighWebSocketAuthFailures
        expr: rate(security_websocket_auth_failures_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: websocket
          category: security
        annotations:
          summary: "High WebSocket authentication failures"
          description: "WebSocket authentication failures are occurring at {{ $value }} per second, indicating potential security issues."

  - name: certificate_security_alerts
    rules:
      # Certificate Expiration Monitoring
      - alert: CertificateExpiresWithin30Days
        expr: (x509_cert_expiry - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          category: certificate
        annotations:
          summary: "Certificate expiring within 30 days"
          description: "Certificate {{ $labels.cn }} expires in {{ $value }} days. Consider renewing the certificate soon."

      - alert: CertificateExpiresWithin7Days  
        expr: (x509_cert_expiry - time()) / 86400 < 7
        for: 1h
        labels:
          severity: critical
          category: certificate
        annotations:
          summary: "Certificate expiring within 7 days"
          description: "Certificate {{ $labels.cn }} expires in {{ $value }} days. Immediate action required to renew the certificate."

      - alert: CertificateExpired
        expr: (x509_cert_expiry - time()) < 0
        for: 0s
        labels:
          severity: critical
          category: certificate
        annotations:
          summary: "Certificate has expired"
          description: "Certificate {{ $labels.cn }} has expired {{ $value }} seconds ago. Service may be unavailable."

  - name: infrastructure_security_alerts
    rules:
      # Container Security
      - alert: ContainerSecurityViolation
        expr: increase(security_events_total{event_type="container_violation"}[5m]) > 0
        for: 0s
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "Container security violation detected"
          description: "A container security violation has been detected. Review container security policies and access controls."

      # Network Security
      - alert: SuspiciousNetworkActivity
        expr: rate(security_events_total{event_type="network_anomaly"}[5m]) > 1
        for: 2m
        labels:
          severity: warning
          category: network
        annotations:
          summary: "Suspicious network activity detected"
          description: "Suspicious network activity has been detected at {{ $value }} events per second."

      # Service Health from Security Perspective
      - alert: CriticalServiceDown
        expr: up{job=~"api|coordination-service|grafana|prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Critical service is down"
          description: "Critical service {{ $labels.job }} is down for more than 1 minute. This may impact security monitoring capabilities."

  - name: compliance_alerts
    rules:
      # Security Compliance Monitoring
      - alert: SecurityAuditRequired
        expr: time() - security_last_audit_timestamp > 604800  # 1 week
        for: 1h
        labels:
          severity: warning
          category: compliance
        annotations:
          summary: "Security audit is overdue"
          description: "Last security audit was performed more than 1 week ago. Consider scheduling a security audit."

      - alert: UnauthorizedAccessAttempt
        expr: rate(http_requests_total{status_code="403"}[5m]) > 5
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "Unauthorized access attempts (403 status) are occurring at {{ $value }} per second for more than 2 minutes."

      - alert: SecurityConfigurationDrift
        expr: security_configuration_compliance_score < 0.9
        for: 5m
        labels:
          severity: warning
          category: compliance
        annotations:
          summary: "Security configuration compliance score is low"
          description: "Security configuration compliance score is {{ $value }}, below the required 90% threshold."