server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # AI Workflow Engine Application Logs
  - job_name: ai-workflow-engine-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-workflow-engine-api
          service: api
          __path__: /app/logs/api*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            message: message
            request_id: request_id
            user_id: user_id
            trace_id: trace_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          request_id:
          user_id:

  - job_name: ai-workflow-engine-worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-workflow-engine-worker
          service: worker
          __path__: /app/logs/worker*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            message: message
            task_id: task_id
            task_name: task_name
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          task_name:

  - job_name: ai-workflow-engine-webui
    static_configs:
      - targets:
          - localhost
        labels:
          job: ai-workflow-engine-webui
          service: webui
          __path__: /app/logs/webui*.log

  # Security Events
  - job_name: security-events
    static_configs:
      - targets:
          - localhost
        labels:
          job: security-events
          service: security
          __path__: /app/logs/security*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            event_type: event_type
            message: message
            ip_address: ip_address
            user_id: user_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          event_type:

  # Performance Logs
  - job_name: performance-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: performance-logs
          service: performance
          __path__: /app/logs/performance*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            event_type: event_type
            duration_seconds: duration_seconds
            service: service
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          event_type:
          service:

  # Business Event Logs
  - job_name: business-events
    static_configs:
      - targets:
          - localhost
        labels:
          job: business-events
          service: business
          __path__: /app/logs/business*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            event_type: event_type
            user_id: user_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          event_type:

  # Docker Container Logs
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
          source: content
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          fallback_formats:
            - RFC3339
            - "2006-01-02T15:04:05.000000000Z07:00"
      - labels:
          level:
          service:
          container:
          stream:

  # System Logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          service: system
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+)(\[(?P<pid>\d+)\])?\:\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 'Jan 2 15:04:05'
          location: 'UTC'
      - labels:
          hostname:
          service:

  # Auth Logs
  - job_name: auth
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth
          service: auth
          __path__: /var/log/auth.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+)(\[(?P<pid>\d+)\])?\:\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: 'Jan 2 15:04:05'
          location: 'UTC'
      - labels:
          hostname:
          service: