version: '3.8'
services:
  api:
    restart: unless-stopped
    networks: 
      - ai_workflow_engine_net
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: ai_workflow_engine/api
    security_opt:
    - apparmor:unconfined
    command:
    - sh
    - -c
    - |
      export POSTGRES_PASSWORD=$$(cat /run/secrets/POSTGRES_PASSWORD)
      export REDIS_PASSWORD=$$(cat /run/secrets/REDIS_PASSWORD)  
      export JWT_SECRET_KEY=$$(cat /run/secrets/JWT_SECRET_KEY)
      export API_KEY=$$(cat /run/secrets/API_KEY)
      export QDRANT_API_KEY=$$(cat /run/secrets/QDRANT_API_KEY)
      export REDIS_URL="redis://lwe-app:$$REDIS_PASSWORD@redis:6379/0"
      export DATABASE_URL="postgresql+psycopg2://app_user:$$POSTGRES_PASSWORD@pgbouncer:6432/ai_workflow_db?sslmode=require"
      export PYTHONPATH=/project/app
      exec uvicorn api.emergency_main:app --host 0.0.0.0 --port 8000
    volumes:
    - type: volume
      source: certs
      target: /tmp/certs-volume
      read_only: true
    - .:/project:rw
    secrets:
    - POSTGRES_PASSWORD
    - REDIS_PASSWORD
    - JWT_SECRET_KEY
    - CSRF_SECRET_KEY
    - QDRANT_API_KEY
    - API_KEY
    - admin_email
    - admin_password
    - google_client_id
    - google_client_secret
    env_file:
    - .env
    - local.env
    environment:
    - GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
    - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google_client_secret
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=app_user
    - POSTGRES_PORT=5432
    - PYTHONPATH=/project/app
    - OLLAMA_API_BASE_URL=http://ollama:11434
    - POSTGRES_DB=ai_workflow_db
    - OLLAMA_GENERATION_MODEL_NAME=llama3.2:3b
    - SERVICE_NAME=api
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_DB=0
    working_dir: /project/app
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:8000/health --max-time 5 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"

networks:
  ai_workflow_engine_net:
    external: true
    name: ai-workflow-engine-net

volumes:
  certs: null

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/postgres_password.txt
  REDIS_PASSWORD:
    file: ./secrets/redis_password.txt
  JWT_SECRET_KEY:
    file: ./secrets/jwt_secret_key.txt
  CSRF_SECRET_KEY:
    file: ./secrets/csrf_secret_key.txt
  QDRANT_API_KEY:
    file: ./secrets/qdrant_api_key.txt
  API_KEY:
    file: ./secrets/api_key.txt
  admin_email:
    file: ./secrets/admin_email.txt
  admin_password:
    file: ./secrets/admin_password.txt
  google_client_id:
    file: ./secrets/google_client_id.txt
  google_client_secret:
    file: ./secrets/google_client_secret.txt