# Simple production deployment for Command & Independent Thought RTS
version: '3.8'

services:
  # RTS Game Application
  game:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: rts-game-production
    ports:
      - "80:8080"
      - "3080:8080"
    environment:
      - NODE_ENV=production
      - VERSION=v1.0.0-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "service=rts-game"
      - "environment=production"
      - "version=v1.0.0-production"

  # Health monitoring (optional, simple)
  monitor:
    image: nginx:alpine
    container_name: rts-monitor
    ports:
      - "8081:80"
    volumes:
      - ./monitoring-simple.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
    depends_on:
      - game

networks:
  default:
    name: rts-network