# config/qdrant/config-mtls.yaml
service:
  # API key is read from file via QDRANT__SERVICE__API_KEY_FILE environment variable
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
storage:
  storage_path: /qdrant/storage
log_level: INFO
tls:
  enabled: true
  cert: /etc/certs/qdrant/unified-cert.pem
  key: /etc/certs/qdrant/unified-key.pem
  ca_cert: /etc/certs/qdrant/rootCA.pem
  # mTLS specific settings
  verify_client: true