# Orchestration Patterns Configuration
# Defines workflow patterns and coordination strategies for the agentic workflow engine

orchestration_patterns:
  version: "2.0.0"
  last_updated: "2025-08-12T00:00:00Z"
  
  workflow_templates:
    complex_feature_implementation:
      name: "Complex Feature Implementation"
      agent_count: 20
      estimated_duration: "2-4 hours"
      phases:
        - phase: "setup"
          agents: ["agent-integration-orchestrator", "evidence-auditor", "orchestration-todo-manager", "context-compression-agent"]
          duration: "15 minutes"
        - phase: "discovery"
          agents: ["codebase-research-analyst", "schema-database-expert", "security-vulnerability-scanner", "enhanced-research-coordinator"]
          parallel: true
          duration: "30 minutes"
        - phase: "implementation"
          streams:
            backend: ["backend-gateway-expert", "schema-database-expert", "python-refactoring-architect", "performance-profiler"]
            frontend: ["webui-architect", "frictionless-ux-architect", "whimsy-ui-creator", "ui-regression-debugger"]
            infrastructure: ["deployment-orchestrator", "k8s-architecture-specialist", "monitoring-analyst"]
            security: ["security-validator", "security-vulnerability-scanner", "code-quality-guardian"]
          parallel: true
          duration: "90 minutes"
        - phase: "validation"
          agents: ["test-automation-engineer", "user-experience-auditor", "security-validator", "orchestration-auditor"]
          duration: "45 minutes"
    
    system_integration:
      name: "System Integration"
      agent_count: 18
      estimated_duration: "1-3 hours"
      phases:
        - phase: "analysis"
          agents: ["fullstack-communication-auditor", "dependency-analyzer", "performance-profiler"]
          duration: "20 minutes"
        - phase: "integration"
          agents: ["backend-gateway-expert", "schema-database-expert", "infrastructure-orchestrator", "deployment-orchestrator"]
          parallel: true
          duration: "60 minutes"
        - phase: "testing"
          agents: ["test-automation-engineer", "production-endpoint-validator", "security-validator"]
          duration: "40 minutes"
    
    performance_optimization:
      name: "Performance Optimization"
      agent_count: 16
      estimated_duration: "1-2 hours"
      phases:
        - phase: "profiling"
          agents: ["performance-profiler", "monitoring-analyst", "codebase-research-analyst"]
          duration: "30 minutes"
        - phase: "optimization"
          agents: ["python-refactoring-architect", "backend-gateway-expert", "schema-database-expert"]
          parallel: true
          duration: "60 minutes"
        - phase: "validation"
          agents: ["performance-profiler", "test-automation-engineer"]
          duration: "30 minutes"

  coordination_strategies:
    parallel_execution:
      max_concurrent_agents: 8
      resource_constraints:
        cpu_intensive: 3
        memory_intensive: 4
        network_intensive: 4
        context_optimized: 8
      
    synchronization_points:
      - name: "api_contracts"
        description: "API interface definitions completed"
        required_agents: ["backend-gateway-expert", "webui-architect"]
      - name: "schema_changes"
        description: "Database schema modifications finalized"
        required_agents: ["schema-database-expert"]
      - name: "security_clearance"
        description: "Security validation passed"
        required_agents: ["security-validator", "security-vulnerability-scanner"]
    
    failure_recovery:
      retry_strategy: "exponential_backoff"
      max_retries: 3
      fallback_agents:
        "codebase-research-analyst": ["enhanced-research-coordinator", "smart-search-agent"]
        "performance-profiler": ["monitoring-analyst"]
        "security-validator": ["security-vulnerability-scanner"]

  context_optimization:
    compression_targets:
      discovery_phase: 0.75
      implementation_phase: 0.85
      validation_phase: 0.80
    
    token_limits:
      per_agent: 4000
      per_stream: 12000
      total_workflow: 48000
    
    compression_agents:
      primary: "context-compression-agent"
      fallback: "content-compressor"
      batch_operations: "parallel-file-manager"

  evidence_collection:
    mandatory_evidence:
      - performance_metrics
      - test_results
      - security_scan_results
      - deployment_validation
      - user_experience_validation
    
    cross_verification:
      minimum_validators: 2
      evidence_types: ["metrics", "artifacts", "systems", "tests"]
      validation_threshold: 0.95

  redis_coordination:
    connection_settings:
      pool_size: 50
      timeout: 30
      retry_attempts: 3
    
    key_patterns:
      workflow_state: "workflow:{workflow_id}:state"
      agent_status: "agent:{agent_id}:status"
      sync_points: "sync:{workflow_id}:{point_name}"
      evidence: "evidence:{workflow_id}:{type}"
    
    atomic_operations:
      enabled: true
      transaction_timeout: 10
      rollback_on_failure: true