"""Add expert group model configuration fields

Revision ID: b0f9ada0f772
Revises: b57ff37f6545
Create Date: 2025-08-02 10:28:17.043401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f9ada0f772'
down_revision: Union[str, Sequence[str], None] = 'b57ff37f6545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project_manager_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('technical_expert_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_analyst_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('creative_director_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('research_specialist_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('planning_expert_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('socratic_expert_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wellbeing_coach_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('personal_assistant_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('data_analyst_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('output_formatter_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('quality_assurance_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quality_assurance_model')
    op.drop_column('users', 'output_formatter_model')
    op.drop_column('users', 'data_analyst_model')
    op.drop_column('users', 'personal_assistant_model')
    op.drop_column('users', 'wellbeing_coach_model')
    op.drop_column('users', 'socratic_expert_model')
    op.drop_column('users', 'planning_expert_model')
    op.drop_column('users', 'research_specialist_model')
    op.drop_column('users', 'creative_director_model')
    op.drop_column('users', 'business_analyst_model')
    op.drop_column('users', 'technical_expert_model')
    op.drop_column('users', 'project_manager_model')
    # ### end Alembic commands ###
