"""Add user-level web search API configuration

Revision ID: b57ff37f6545
Revises: 1e0c093dc24e
Create Date: 2025-07-30 23:06:10.710368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57ff37f6545'
down_revision: Union[str, Sequence[str], None] = '1e0c093dc24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_devices', sa.Column('refresh_token_hash', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('web_search_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('web_search_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'web_search_api_key')
    op.drop_column('users', 'web_search_provider')
    op.drop_column('registered_devices', 'refresh_token_hash')
    # ### end Alembic commands ###
