unified_orchestration_configuration:
  version: "2.0"
  last_updated: "2025-08-13"
  incident_driven_update: "20-hour-outage-prevention"
  
  orchestration_phases:
    phase_0:
      name: "Todo Context Integration & System Health Check"
      agents:
        - orchestration-todo-manager
        - infrastructure-recovery-agent  # NEW: Verify system health before starting
      validation:
        - all_critical_services_running: true
        - production_site_accessible: true
        - no_active_incidents: true
      evidence_required:
        - docker_ps_output
        - curl_production_check
        - health_endpoint_results
    
    phase_1:
      name: "Agent Ecosystem Validation"
      agents:
        - agent-integration-orchestrator
      enhanced_checks:
        - validate_recovery_agent_available: true
        - verify_monitoring_active: true
        - check_communication_channels: true
    
    phase_2:
      name: "Strategic Intelligence Planning"
      agents:
        - project-orchestrator
        - enhanced-nexus-synthesis-agent
      deployment_safety_requirements:
        - map_service_dependencies: true
        - identify_protected_services: true
        - create_rollback_plan: true
    
    phase_3:
      name: "Multi-Domain Research Discovery"
      parallel_agents:
        - codebase-research-analyst
        - schema-database-expert
        - security-validator
        - performance-profiler
        - smart-search-agent
        - infrastructure-recovery-agent  # NEW: Baseline current infrastructure state
      infrastructure_baseline:
        - document_current_services: true
        - capture_current_health_metrics: true
        - identify_critical_dependencies: true
    
    phase_4:
      name: "Context Synthesis & Compression"
      agents:
        - nexus-synthesis-agent
        - context-compression-agent
        - document-compression-agent
      include_infrastructure_context:
        - service_dependency_map: true
        - critical_service_list: true
        - recovery_procedures: true
    
    phase_5:
      name: "Parallel Implementation Execution"
      implementation_safety:
        pre_implementation_checks:
          - verify_no_service_removal_without_replacement: true
          - validate_dependency_preservation: true
          - confirm_rollback_capability: true
        
        during_implementation_monitoring:
          - track_service_state_changes: true
          - monitor_health_endpoints: true
          - detect_service_failures: true
        
        specialist_coordination:
          - backend-gateway-expert
          - webui-architect
          - infrastructure-recovery-agent  # Monitor during implementation
          - monitoring-analyst
    
    phase_6:
      name: "Comprehensive Evidence-Based Validation"
      mandatory_validators:
        - production-endpoint-validator
        - user-experience-auditor
        - infrastructure-recovery-agent  # NEW: Validate all services operational
        - ui-regression-debugger
        - performance-profiler
        - code-quality-guardian
      
      validation_requirements:
        infrastructure_validation:
          all_containers_running:
            check: "docker ps"
            evidence: "container list with health status"
          service_health_checks:
            check: "curl health endpoints"
            evidence: "HTTP response codes and body"
          database_connectivity:
            check: "connection test"
            evidence: "successful query result"
          redis_connectivity:
            check: "redis ping"
            evidence: "PONG response"
        
        user_accessibility_validation:
          production_url_accessible:
            check: "curl https://aiwfe.com"
            evidence: "200 OK response"
          login_workflow_functional:
            check: "playwright automation"
            evidence: "screenshot of successful login"
          critical_features_working:
            check: "end-to-end test"
            evidence: "test execution logs"
        
        performance_validation:
          page_load_time:
            threshold: "<3 seconds"
            evidence: "performance metrics"
          api_response_time:
            threshold: "<500ms"
            evidence: "response time logs"
      
      failure_handling:
        any_validation_failure:
          action: "trigger_recovery_procedures"
          notification: "alert_all_agents"
          iteration: "restart_from_phase_0"
    
    phase_7:
      name: "Decision & Iteration Control"
      agents:
        - orchestration-auditor-v2
        - infrastructure-recovery-agent  # Participate in go/no-go decision
      
      decision_criteria:
        continue_conditions:
          - all_validations_passed: true
          - all_services_healthy: true
          - production_accessible: true
          - evidence_complete: true
        
        iteration_conditions:
          - any_validation_failed: true
          - service_unavailable: true
          - evidence_missing: true
          - performance_degraded: true
        
        abort_conditions:
          - max_iterations_reached: true
          - critical_service_unrecoverable: true
          - data_corruption_detected: true
    
    phase_8:
      name: "Atomic Version Control Synchronization"
      agents:
        - atomic-git-synchronizer
      pre_commit_validation:
        - verify_no_service_disruption: true
        - confirm_all_tests_passing: true
        - validate_production_stable: true
      commit_requirements:
        - include_recovery_procedures: true
        - document_infrastructure_changes: true
        - reference_validation_evidence: true
    
    phase_9:
      name: "Meta-Orchestration Audit & Learning"
      agents:
        - orchestration-auditor
        - execution-conflict-detector
        - evidence-auditor
        - infrastructure-recovery-agent  # NEW: Final health verification
      
      mandatory_final_checks:
        production_accessibility:
          - curl_https_aiwfe_com: "must return 200"
          - user_can_login: "must succeed"
          - critical_features_functional: "must work"
        
        infrastructure_health:
          - all_containers_running: "must be true"
          - no_restart_loops: "must be verified"
          - resource_usage_normal: "must be within limits"
        
        evidence_completeness:
          - all_phases_have_evidence: "must be documented"
          - evidence_shows_success: "must be verifiable"
          - no_false_positives: "must be validated"
      
      learning_capture:
        - identify_failure_patterns: true
        - update_recovery_procedures: true
        - improve_validation_checks: true
        - enhance_monitoring_rules: true
  
  critical_safeguards:
    never_remove_without_replacement:
      services:
        - webui
        - backend
        - database
        - redis
      enforcement: "block_deployment_if_violated"
    
    mandatory_health_monitoring:
      interval: 60  # seconds
      services: "all"
      action_on_failure: "immediate_recovery"
    
    deployment_protection:
      backup_before_update: true
      validate_after_update: true
      rollback_on_failure: true
      max_downtime_allowed: 300  # seconds (5 minutes)
    
    evidence_requirements:
      every_claim_needs_evidence: true
      evidence_must_be_current: true
      evidence_must_show_success: true
      false_claims_trigger_audit: true
  
  success_metrics:
    zero_undetected_outages:
      monitoring_interval: 60  # seconds
      max_detection_time: 300  # seconds (5 minutes)
    
    100_percent_validation_accuracy:
      no_false_positives: true
      no_false_negatives: true
      evidence_based_claims: true
    
    automatic_recovery_success:
      target_success_rate: 95  # percent
      max_recovery_time: 600  # seconds (10 minutes)
    
    deployment_safety:
      zero_production_disruptions: true
      all_rollbacks_successful: true
      no_data_loss: true