x-logging: &id001
  driver: json-file
  options:
    max-size: 10m
    max-file: '3'
x-base-service-properties:
  restart: unless-stopped
  networks: &id002
  - ai_workflow_engine_net
  logging: *id001
x-gpu-deploy:
  deploy: &id003
    resources:
      reservations:
        devices:
        - driver: nvidia
          count: all
          capabilities:
          - gpu
networks:
  ai_workflow_engine_net:
    external: true
    name: ai-workflow-engine-net
  shared-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ai-workflow-shared
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
volumes:
  postgres_data: null
  redis_data: null
  qdrant_data: null
  prometheus_data: null
  grafana_data: null
  alertmanager_data: null
  ollama_data: null
  certs: null
  webui_node_modules: {}
  webui_next_node_modules: {}
  jaeger_data: null
  caddy_data: null
  caddy_config: null
  loki_data: null
  elasticsearch_data: null
  kibana_data: null
  health_monitor_data: null
  # New intelligent services volumes
  rabbitmq_data: null
  kafka_data: null
  zookeeper_data: null
  voice_models: null
  recommendation_models: null
