version: '3.8'

services:
  # Just Caddy for Let's Encrypt certificate testing
  caddy_reverse_proxy:
    image: caddy:2-alpine
    container_name: caddy_letsencrypt_test
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Admin API
    volumes:
      - ./config/caddy/Caddyfile-letsencrypt-test:/etc/caddy/Caddyfile:ro
      - ./test_html:/usr/share/nginx/html:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs/caddy:/var/log/caddy
    environment:
      - DOMAIN=${DOMAIN:-aiwfe.com}
      - DNS_PROVIDER=${DNS_PROVIDER:-cloudflare}
      - DNS_API_TOKEN=${DNS_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL:-markuszvirbulis@gmail.com}
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Simple test API endpoint
  test_api:
    image: nginx:alpine
    container_name: test_api
    restart: unless-stopped
    volumes:
      - ./test_html:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  caddy_data:
  caddy_config: