# This file is used exclusively for the one-time certificate generation task.
version: '3.8'

services:
  certs-init: # This service is for one-time certificate generation.
    build:
      context: .
      dockerfile: ./docker/certs-init/Dockerfile
    image: ai_workflow_engine/certs-init
    container_name: ai_workflow_engine-certs-init-temp # Temporary name
    # The command is passed by the _setup_secrets_and_certs.sh script.
    volumes:
      # Mount the shared named volume where certificates will be stored.
      - certs:/certs

# Define the named volume here so this file is self-contained and can be
# run independently to create the volume if it doesn't exist.
volumes:
  certs:
    driver: local