groups:
  - name: authentication_alerts
    rules:
      # High Authentication Failure Rate
      - alert: HighAuthFailureRate
        expr: |
          (
            sum(rate(auth_failures_total[5m])) / 
            sum(rate(auth_attempts_total[5m])) * 100
          ) > 10
        for: 2m
        labels:
          severity: warning
          category: security
          component: authentication
        annotations:
          summary: "High authentication failure rate detected"
          description: "Authentication failure rate is {{ $value }}% over the last 5 minutes, exceeding 10% threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-failure-rate"

      # Critical Authentication Failure Rate
      - alert: CriticalAuthFailureRate
        expr: |
          (
            sum(rate(auth_failures_total[5m])) / 
            sum(rate(auth_attempts_total[5m])) * 100
          ) > 25
        for: 1m
        labels:
          severity: critical
          category: security
          component: authentication
        annotations:
          summary: "Critical authentication failure rate detected"
          description: "Authentication failure rate is {{ $value }}% over the last 5 minutes, exceeding critical 25% threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-failure-rate"

      # JWT Secret Key Mismatch
      - alert: JWTSecretKeyMismatch
        expr: increase(auth_secret_key_mismatches_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
          component: jwt
        annotations:
          summary: "JWT SECRET_KEY mismatch detected"
          description: "{{ $value }} JWT SECRET_KEY mismatches detected in the last 5 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/jwt-secret-key"

      # JWT Service Unhealthy
      - alert: JWTServiceUnhealthy
        expr: auth_secret_key_health == 0
        for: 1m
        labels:
          severity: critical
          category: security
          component: jwt
        annotations:
          summary: "JWT consistency service is unhealthy"
          description: "JWT consistency service health check is failing"
          runbook_url: "https://aiwfe.com/docs/runbooks/jwt-service-health"

      # Slow Authentication Performance
      - alert: SlowAuthenticationPerformance
        expr: |
          histogram_quantile(0.95, 
            sum(rate(auth_response_time_seconds_bucket[5m])) by (le)
          ) > 0.05
        for: 5m
        labels:
          severity: warning
          category: performance
          component: authentication
        annotations:
          summary: "Authentication performance is degraded"
          description: "95th percentile authentication response time is {{ $value }}s, exceeding 50ms target"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-performance"

      # Very Slow Authentication
      - alert: VerySlowAuthentication
        expr: |
          histogram_quantile(0.95,
            sum(rate(auth_response_time_seconds_bucket[5m])) by (le)
          ) > 0.1
        for: 2m
        labels:
          severity: critical
          category: performance
          component: authentication
        annotations:
          summary: "Authentication performance is critically slow"
          description: "95th percentile authentication response time is {{ $value }}s, exceeding 100ms critical threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-performance"

      # Excessive Failed Attempts from Single IP
      - alert: ExcessiveFailuresFromIP
        expr: increase(auth_failed_attempts_by_ip_total[5m]) > 20
        for: 1m
        labels:
          severity: critical
          category: security
          component: authentication
        annotations:
          summary: "Excessive authentication failures from single IP"
          description: "IP {{ $labels.client_ip }} has {{ $value }} failed authentication attempts in 5 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/brute-force-protection"

      # JWT Token Validation Failures
      - alert: HighJWTValidationFailures
        expr: |
          (
            sum(rate(auth_jwt_tokens_validated_total{result!="success"}[5m])) /
            sum(rate(auth_jwt_tokens_validated_total[5m])) * 100
          ) > 15
        for: 3m
        labels:
          severity: warning
          category: security
          component: jwt
        annotations:
          summary: "High JWT token validation failure rate"
          description: "JWT validation failure rate is {{ $value }}% over the last 5 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/jwt-validation-failures"

      # WebSocket Authentication Failures
      - alert: WebSocketAuthFailures
        expr: |
          (
            sum(rate(auth_websocket_auth_attempts_total{result="failure"}[5m])) /
            sum(rate(auth_websocket_auth_attempts_total[5m])) * 100
          ) > 20
        for: 5m
        labels:
          severity: warning
          category: security
          component: websocket
        annotations:
          summary: "High WebSocket authentication failure rate"
          description: "WebSocket auth failure rate is {{ $value }}% over the last 5 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/websocket-auth"

      # Bearer Token Consistency Issues
      - alert: BearerTokenConsistencyDegraded
        expr: auth_bearer_token_consistency_score < 90
        for: 5m
        labels:
          severity: warning
          category: security
          component: bearer_token
        annotations:
          summary: "Bearer token consistency score is degraded"
          description: "Bearer token consistency score is {{ $value }}%, below 90% threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/bearer-token-consistency"

      # Critical Bearer Token Issues
      - alert: BearerTokenConsistencyCritical
        expr: auth_bearer_token_consistency_score < 70
        for: 2m
        labels:
          severity: critical
          category: security
          component: bearer_token
        annotations:
          summary: "Bearer token consistency score is critically low"
          description: "Bearer token consistency score is {{ $value }}%, below critical 70% threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/bearer-token-consistency"

      # Authentication Cache Performance
      - alert: LowAuthCacheHitRate
        expr: |
          (
            sum(rate(auth_cache_hits_total[10m])) /
            (sum(rate(auth_cache_hits_total[10m])) + sum(rate(auth_cache_misses_total[10m]))) * 100
          ) < 80
        for: 5m
        labels:
          severity: warning
          category: performance
          component: authentication_cache
        annotations:
          summary: "Authentication cache hit rate is low"
          description: "Authentication cache hit rate is {{ $value }}%, below 80% threshold"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-cache-performance"

      # Authentication Anomaly Detection
      - alert: AuthenticationAnomalyDetected
        expr: increase(auth_anomalies_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          category: security
          component: anomaly_detection
        annotations:
          summary: "Authentication anomaly detected"
          description: "{{ $value }} authentication anomalies detected in the last 5 minutes: {{ $labels.anomaly_type }}"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-anomalies"

      # High Severity Authentication Anomalies
      - alert: CriticalAuthenticationAnomaly
        expr: increase(auth_anomalies_total{severity="high"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: security
          component: anomaly_detection
        annotations:
          summary: "Critical authentication anomaly detected"
          description: "High severity authentication anomaly: {{ $labels.anomaly_type }}"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-anomalies"

      # Performance Target Compliance
      - alert: AuthPerformanceTargetNotMet
        expr: auth_performance_target_compliance{target_type="response_time"} == 0
        for: 10m
        labels:
          severity: warning
          category: performance
          component: authentication
        annotations:
          summary: "Authentication performance target not being met"
          description: "Authentication response time performance target (<50ms) not met for 10 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-performance-targets"

      # Success Rate Target Not Met
      - alert: AuthSuccessRateTargetNotMet
        expr: auth_performance_target_compliance{target_type="success_rate"} == 0
        for: 5m
        labels:
          severity: critical
          category: security
          component: authentication
        annotations:
          summary: "Authentication success rate target not being met"
          description: "Authentication success rate target (>95%) not met for 5 minutes"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-success-rate"

      # No Authentication Activity (System Issue)
      - alert: NoAuthenticationActivity
        expr: |
          sum(rate(auth_attempts_total[5m])) == 0 and 
          sum(rate(app_http_requests_total[5m])) > 0
        for: 10m
        labels:
          severity: critical
          category: system
          component: authentication
        annotations:
          summary: "No authentication activity detected despite traffic"
          description: "No authentication attempts in 10 minutes despite HTTP traffic, possible system issue"
          runbook_url: "https://aiwfe.com/docs/runbooks/auth-system-failure"

  - name: authentication_health_recording_rules
    interval: 30s
    rules:
      # Authentication Success Rate (5m window)
      - record: auth:success_rate_5m
        expr: |
          (
            sum(rate(auth_attempts_total{result="success"}[5m])) /
            sum(rate(auth_attempts_total[5m])) * 100
          )

      # Authentication Failure Rate (5m window)  
      - record: auth:failure_rate_5m
        expr: |
          (
            sum(rate(auth_attempts_total{result="failure"}[5m])) /
            sum(rate(auth_attempts_total[5m])) * 100
          )

      # JWT Validation Success Rate (5m window)
      - record: auth:jwt_validation_success_rate_5m
        expr: |
          (
            sum(rate(auth_jwt_tokens_validated_total{result="success"}[5m])) /
            sum(rate(auth_jwt_tokens_validated_total[5m])) * 100
          )

      # Average Authentication Response Time (5m window)
      - record: auth:avg_response_time_5m
        expr: |
          histogram_quantile(0.5,
            sum(rate(auth_response_time_seconds_bucket[5m])) by (le)
          )

      # 95th Percentile Authentication Response Time (5m window)
      - record: auth:p95_response_time_5m
        expr: |
          histogram_quantile(0.95,
            sum(rate(auth_response_time_seconds_bucket[5m])) by (le)
          )

      # Cache Hit Rate (10m window)
      - record: auth:cache_hit_rate_10m
        expr: |
          (
            sum(rate(auth_cache_hits_total[10m])) /
            (sum(rate(auth_cache_hits_total[10m])) + sum(rate(auth_cache_misses_total[10m]))) * 100
          )