groups:
  - name: calendar_sync_alerts
    rules:
      # Critical Database Schema Errors
      - alert: CalendarSyncSchemaError
        expr: increase(calendar_sync_schema_errors_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: calendar
          component: database
        annotations:
          summary: "Database schema error detected in calendar sync"
          description: "Calendar sync is failing due to database schema errors. Error type: {{ $labels.error_type }}, Table: {{ $labels.table_name }}, Column: {{ $labels.column_name }}. This requires immediate database schema fix."
          runbook_url: "https://docs.aiwfe.com/runbooks/calendar-schema-errors"

      # OAuth Token Scope Column Missing
      - alert: CalendarSyncOAuthTokenScopeError
        expr: increase(calendar_sync_oauth_token_errors_total{error_subtype="missing_scope_column"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: calendar
          component: oauth
        annotations:
          summary: "OAuth token scope column missing in calendar sync"
          description: "Calendar sync failing due to missing 'scope' column in user_oauth_tokens table. User ID: {{ $labels.user_id }}. Database migration required."
          runbook_url: "https://docs.aiwfe.com/runbooks/oauth-token-schema-fix"

      # High Calendar Sync Error Rate
      - alert: CalendarSyncHighErrorRate
        expr: |
          (
            rate(calendar_sync_requests_total{status=~"failure|schema_error|auth_error"}[10m]) / 
            rate(calendar_sync_requests_total[10m])
          ) > 0.5
        for: 5m
        labels:
          severity: high
          service: calendar
          component: sync
        annotations:
          summary: "High error rate in calendar sync operations"
          description: "Calendar sync error rate is {{ $value | humanizePercentage }} over the last 10 minutes. This indicates a systematic issue affecting multiple users."

      # Calendar Sync Performance Degradation
      - alert: CalendarSyncPerformanceDegradation
        expr: |
          (
            histogram_quantile(0.95, rate(calendar_sync_duration_seconds_bucket[10m])) > 
            calendar_sync_baseline_duration_seconds * 3
          ) and calendar_sync_baseline_duration_seconds > 0
        for: 10m
        labels:
          severity: medium
          service: calendar
          component: performance
        annotations:
          summary: "Calendar sync performance degradation detected"
          description: "95th percentile calendar sync duration is {{ $value }}s, which is 3x above baseline of {{ query \"calendar_sync_baseline_duration_seconds\" }}s."

      # Circuit Breaker Opened for Multiple Users
      - alert: CalendarSyncCircuitBreakerMultipleUsers
        expr: count(calendar_sync_circuit_breaker_state == 1) >= 3
        for: 2m
        labels:
          severity: high
          service: calendar
          component: circuit_breaker
        annotations:
          summary: "Calendar sync circuit breakers opened for multiple users"
          description: "{{ $value }} users have calendar sync circuit breakers in open state, indicating widespread sync failures."

      # Calendar Sync Health Score Low
      - alert: CalendarSyncHealthScoreLow
        expr: calendar_sync_health_score{time_window="1h"} < 70
        for: 15m
        labels:
          severity: medium
          service: calendar
          component: health
        annotations:
          summary: "Calendar sync health score is low"
          description: "Calendar sync health score for 1h window is {{ $value }}, indicating degraded service quality."

      # No Calendar Sync Activity
      - alert: CalendarSyncNoActivity
        expr: rate(calendar_sync_requests_total[30m]) == 0
        for: 30m
        labels:
          severity: medium
          service: calendar
          component: availability
        annotations:
          summary: "No calendar sync activity detected"
          description: "No calendar sync requests have been processed in the last 30 minutes. This may indicate service unavailability."

      # Database Schema Error Spike
      - alert: CalendarSyncSchemaErrorSpike
        expr: increase(calendar_sync_schema_errors_total[15m]) >= 10
        for: 0m
        labels:
          severity: critical
          service: calendar
          component: database
        annotations:
          summary: "Spike in calendar sync database schema errors"
          description: "{{ $value }} database schema errors in calendar sync over 15 minutes. This requires immediate investigation and database fix."

      # Consecutive Failures Per User
      - alert: CalendarSyncUserConsecutiveFailures
        expr: calendar_sync_consecutive_failures >= 5
        for: 5m
        labels:
          severity: high
          service: calendar
          component: user_experience
        annotations:
          summary: "User experiencing consecutive calendar sync failures"
          description: "User {{ $labels.user_id }} has {{ $value }} consecutive calendar sync failures. User impact is high."

      # Authentication Errors Pattern
      - alert: CalendarSyncAuthErrorPattern
        expr: increase(calendar_sync_requests_total{status="auth_error"}[10m]) >= 5
        for: 5m
        labels:
          severity: high
          service: calendar
          component: authentication
        annotations:
          summary: "Pattern of authentication errors in calendar sync"
          description: "{{ $value }} authentication errors in calendar sync over 10 minutes. OAuth tokens may need refreshing or reconnection required."

  - name: calendar_sync_database_specific
    rules:
      # Specific UndefinedColumn Error Pattern
      - alert: CalendarSyncUndefinedColumnError
        expr: increase(calendar_sync_schema_errors_total{error_type="undefined_column", column_name="scope"}[1m]) > 0
        for: 0m
        labels:
          severity: critical
          service: calendar
          component: database
          fix_priority: immediate
        annotations:
          summary: "CRITICAL: user_oauth_tokens.scope column missing"
          description: "Database query failing because user_oauth_tokens.scope column does not exist. This is the exact error pattern from recent logs. Database migration must be executed immediately."
          fix_command: "Run database migration to add scope column to user_oauth_tokens table"
          affected_endpoint: "/api/v1/calendar/sync/auto"

      # PostgreSQL Specific Error Pattern
      - alert: CalendarSyncPostgreSQLSchemaError
        expr: increase(calendar_sync_schema_errors_total{table_name="user_oauth_tokens"}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          service: calendar
          component: database
          database: postgresql
        annotations:
          summary: "PostgreSQL schema error in user_oauth_tokens table"
          description: "PostgreSQL is reporting schema errors for user_oauth_tokens table in calendar sync operations. Column structure mismatch detected."

  - name: calendar_sync_recovery_monitoring
    rules:
      # Post-Fix Validation
      - alert: CalendarSyncFixValidation
        expr: |
          (
            rate(calendar_sync_requests_total{status="success"}[10m]) /
            rate(calendar_sync_requests_total[10m])
          ) > 0.95 and 
          increase(calendar_sync_schema_errors_total[10m]) == 0
        for: 10m
        labels:
          severity: info
          service: calendar
          component: recovery
        annotations:
          summary: "Calendar sync appears to be healthy post-fix"
          description: "Calendar sync success rate is {{ $value | humanizePercentage }} with no schema errors in the last 10 minutes. Fix appears successful."

      # Success Rate Recovery
      - alert: CalendarSyncSuccessRateRecovery
        expr: |
          (
            rate(calendar_sync_requests_total{status="success"}[5m]) /
            rate(calendar_sync_requests_total[5m])
          ) > calendar_sync_baseline_success_rate * 0.9 and
          calendar_sync_baseline_success_rate > 0
        for: 5m
        labels:
          severity: info
          service: calendar
          component: recovery
        annotations:
          summary: "Calendar sync success rate recovering"
          description: "Calendar sync success rate {{ $value | humanizePercentage }} is approaching baseline of {{ query \"calendar_sync_baseline_success_rate\" | humanizePercentage }}."

  - name: calendar_sync_performance_baselines
    rules:
      # Baseline Performance Recording
      - record: calendar_sync:success_rate_5m
        expr: |
          rate(calendar_sync_requests_total{status="success"}[5m]) /
          rate(calendar_sync_requests_total[5m])

      - record: calendar_sync:error_rate_5m
        expr: |
          rate(calendar_sync_requests_total{status=~"failure|schema_error|auth_error"}[5m]) /
          rate(calendar_sync_requests_total[5m])

      - record: calendar_sync:p95_duration_5m
        expr: histogram_quantile(0.95, rate(calendar_sync_duration_seconds_bucket[5m]))

      - record: calendar_sync:p50_duration_5m
        expr: histogram_quantile(0.50, rate(calendar_sync_duration_seconds_bucket[5m]))

      - record: calendar_sync:schema_error_rate_5m
        expr: rate(calendar_sync_schema_errors_total[5m])

      - record: calendar_sync:events_per_sync_5m
        expr: rate(calendar_sync_events_synced_sum[5m]) / rate(calendar_sync_events_synced_count[5m])