groups:
  - name: cognitive_services
    interval: 30s
    rules:
      # Service Health Rules
      - alert: CognitiveServiceDown
        expr: service_health_status{component="main"} == 0
        for: 2m
        labels:
          severity: critical
          component: cognitive_services
        annotations:
          summary: "Cognitive service {{ $labels.service }} is down"
          description: "{{ $labels.service }} has been unhealthy for more than 2 minutes"
          action: "Check service logs and consider automatic recovery"

      - alert: CognitiveServiceHighResponseTime
        expr: rate(service_health_check_duration_seconds_sum[5m]) / rate(service_health_check_duration_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
          component: cognitive_services
        annotations:
          summary: "High response time for {{ $labels.service }}"
          description: "{{ $labels.service }} average response time is {{ $value }}s (threshold: 2s)"
          
      - alert: CognitiveServiceFlapping
        expr: changes(service_health_status[10m]) > 4
        for: 5m
        labels:
          severity: warning
          component: cognitive_services
        annotations:
          summary: "Service {{ $labels.service }} is flapping"
          description: "{{ $labels.service }} health status changed {{ $value }} times in 10 minutes"

      # Recovery Monitoring
      - alert: RecoveryAttemptsHigh
        expr: rate(service_recovery_attempts_total[5m]) > 0.1
        for: 10m
        labels:
          severity: warning
          component: recovery
        annotations:
          summary: "High recovery attempt rate for {{ $labels.service }}"
          description: "{{ $labels.service }} has {{ $value }} recovery attempts per second"

      - alert: RecoveryFailed
        expr: increase(service_recovery_attempts_total{action="restart_failed"}[5m]) > 2
        for: 2m
        labels:
          severity: critical
          component: recovery
        annotations:
          summary: "Recovery failed for {{ $labels.service }}"
          description: "Multiple recovery attempts failed for {{ $labels.service }}"

      # Integration Health
      - alert: LearningServiceIntegrationIssue
        expr: service_health_status{service="learning-service"} == 0 and up{job="learning-service"} == 1
        for: 5m
        labels:
          severity: warning
          component: integration
        annotations:
          summary: "Learning service integration issues detected"
          description: "Learning service container is up but health check is failing"

      - alert: ReasoningServiceIntegrationIssue
        expr: service_health_status{service="reasoning-service"} == 0 and up{job="reasoning-service"} == 1
        for: 5m
        labels:
          severity: warning
          component: integration
        annotations:
          summary: "Reasoning service integration issues detected"
          description: "Reasoning service container is up but health check is failing"

      - alert: CoordinationServiceDown
        expr: service_health_status{service="coordination-service"} == 0
        for: 3m
        labels:
          severity: critical
          component: coordination
        annotations:
          summary: "Coordination service is down"
          description: "Critical coordination service has been down for 3 minutes"
          action: "Immediate recovery required - this affects all agent coordination"

      - alert: HybridMemoryDatabaseIssue
        expr: service_health_status{service="hybrid-memory-service"} == 0
        for: 5m
        labels:
          severity: critical
          component: memory
        annotations:
          summary: "Hybrid memory service database issues"
          description: "Hybrid memory service cannot connect to database"
          action: "Check PostgreSQL connectivity and credentials"

      # Infrastructure Dependencies
      - alert: RedisConnectionFailure
        expr: service_health_status{service="infra_redis"} == 0
        for: 2m
        labels:
          severity: critical
          component: infrastructure
        annotations:
          summary: "Redis connection failure"
          description: "Cannot connect to Redis - affects all cognitive services"

      - alert: QdrantVectorDBDown
        expr: service_health_status{service="infra_qdrant"} == 0
        for: 5m
        labels:
          severity: high
          component: infrastructure
        annotations:
          summary: "Qdrant vector database is down"
          description: "Qdrant is unavailable - affects learning and memory services"

      - alert: Neo4jGraphDBDown
        expr: service_health_status{service="infra_neo4j"} == 0
        for: 5m
        labels:
          severity: high
          component: infrastructure
        annotations:
          summary: "Neo4j graph database is down"
          description: "Neo4j is unavailable - affects learning service knowledge graph"

      - alert: OllamaLLMServiceDown
        expr: service_health_status{service="infra_ollama"} == 0
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Ollama LLM service is down"
          description: "Ollama is unavailable - affects reasoning capabilities"

      # Alert Fatigue Prevention
      - alert: HighAlertRate
        expr: rate(health_alerts_triggered_total[5m]) > 0.5
        for: 10m
        labels:
          severity: info
          component: monitoring
        annotations:
          summary: "High alert rate detected"
          description: "Alert rate is {{ $value }} per second - possible alert storm"
          action: "Review alert thresholds and consider temporary suppression"

      # Service Reliability Tracking
      - alert: ServiceReliabilityLow
        expr: avg_over_time(service_health_status[1h]) < 0.95
        for: 15m
        labels:
          severity: warning
          component: reliability
        annotations:
          summary: "{{ $labels.service }} reliability below SLA"
          description: "{{ $labels.service }} has {{ $value | humanizePercentage }} uptime in the last hour (SLA: 95%)"

      # Critical Path Monitoring
      - alert: CriticalPathFailure
        expr: |
          (service_health_status{service="coordination-service"} == 0) or
          (service_health_status{service="learning-service"} == 0) or
          (service_health_status{service="reasoning-service"} == 0)
        for: 1m
        labels:
          severity: critical
          component: critical_path
        annotations:
          summary: "Critical cognitive service path failure"
          description: "One or more critical cognitive services are down"
          action: "Immediate intervention required - core functionality impacted"