groups:
  # ==============================================================================
  # CONSOLIDATED 8-SERVICE ARCHITECTURE MONITORING RULES
  # ==============================================================================
  
  - name: consolidated.services.availability
    interval: 30s
    rules:
      # API Gateway Health (Primary Entry Point)
      - alert: APIGatewayDown
        expr: up{job="aiwfe-api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
          service: api-gateway
          category: availability
          consolidated: "true"
        annotations:
          summary: "API Gateway is down"
          description: "API Gateway service {{ $labels.instance }} is not responding"
          impact: "All API requests failing, complete service outage"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/api-gateway-down"

      # WebUI Service Health
      - alert: WebUIDown
        expr: up{job="aiwfe-webui"} == 0
        for: 2m
        labels:
          severity: high
          service: webui
          category: availability
          consolidated: "true"
        annotations:
          summary: "WebUI service is down"
          description: "WebUI service {{ $labels.instance }} is not responding"
          impact: "Users cannot access web interface"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/webui-down"

      # Integration Service Health (Google Services, External APIs)
      - alert: IntegrationServiceDown
        expr: up{job="integration-service"} == 0
        for: 3m
        labels:
          severity: high
          service: integration
          category: availability
          consolidated: "true"
        annotations:
          summary: "Integration service is down"
          description: "Integration service {{ $labels.instance }} is not responding"
          impact: "External API integrations failing, no Google Calendar sync"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/integration-down"

      # Reasoning Service Health (AI Processing)
      - alert: ReasoningServiceDown
        expr: up{job="reasoning-service"} == 0
        for: 2m
        labels:
          severity: critical
          service: reasoning
          category: availability
          consolidated: "true"
        annotations:
          summary: "Reasoning service is down"
          description: "Reasoning service {{ $labels.instance }} is not responding"
          impact: "AI workflow processing stopped, all reasoning tasks failing"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/reasoning-down"

      # Metrics Aggregator Health
      - alert: MetricsAggregatorDown
        expr: up{job="metrics-aggregator"} == 0
        for: 5m
        labels:
          severity: medium
          service: metrics
          category: availability
          consolidated: "true"
        annotations:
          summary: "Metrics aggregator is down"
          description: "Metrics aggregator {{ $labels.instance }} is not responding"
          impact: "Business metrics collection stopped, analytics unavailable"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/metrics-down"

  # ==============================================================================
  # CONSOLIDATION PERFORMANCE RULES
  # ==============================================================================

  - name: consolidated.services.performance
    interval: 60s
    rules:
      # Service Consolidation Resource Efficiency
      - record: consolidation:cpu_efficiency
        expr: |
          (
            sum(rate(container_cpu_usage_seconds_total{name=~".*aiwfe.*"}[5m])) by (instance) /
            sum(container_spec_cpu_quota{name=~".*aiwfe.*"} / container_spec_cpu_period{name=~".*aiwfe.*"}) by (instance)
          ) * 100

      - record: consolidation:memory_efficiency
        expr: |
          (
            sum(container_memory_usage_bytes{name=~".*aiwfe.*"}) by (instance) /
            sum(container_spec_memory_limit_bytes{name=~".*aiwfe.*"}) by (instance)
          ) * 100

      # Resource Efficiency Alert (Target: 70-80% utilization)
      - alert: ConsolidationResourceUnderutilization
        expr: consolidation:cpu_efficiency < 40 or consolidation:memory_efficiency < 50
        for: 10m
        labels:
          severity: medium
          category: efficiency
          consolidated: "true"
        annotations:
          summary: "Consolidated services are underutilizing resources"
          description: "CPU efficiency: {{ $value }}%, Memory efficiency: {{ $value }}%"
          impact: "Potential cost optimization opportunity"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/resource-underutilization"

      - alert: ConsolidationResourceOverutilization
        expr: consolidation:cpu_efficiency > 85 or consolidation:memory_efficiency > 90
        for: 5m
        labels:
          severity: high
          category: performance
          consolidated: "true"
        annotations:
          summary: "Consolidated services are overutilizing resources"
          description: "CPU efficiency: {{ $value }}%, Memory efficiency: {{ $value }}%"
          impact: "Performance degradation risk, may need resource scaling"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/resource-overutilization"

  # ==============================================================================
  # SERVICE INTEGRATION HEALTH RULES
  # ==============================================================================

  - name: consolidated.services.integration
    interval: 30s
    rules:
      # API Gateway to Backend Services Connectivity
      - alert: ServiceIntegrationFailure
        expr: |
          (
            rate(http_requests_total{job="aiwfe-api-gateway", status=~"5.."}[5m]) /
            rate(http_requests_total{job="aiwfe-api-gateway"}[5m])
          ) * 100 > 5
        for: 3m
        labels:
          severity: high
          category: integration
          consolidated: "true"
        annotations:
          summary: "High error rate in service integration"
          description: "{{ $value }}% of API Gateway requests are failing"
          impact: "Service integration issues affecting user experience"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/integration-failure"

      # Cross-Service Communication Latency
      - alert: HighCrossServiceLatency
        expr: |
          histogram_quantile(0.95, 
            rate(http_request_duration_seconds_bucket{job=~"aiwfe-.*"}[5m])
          ) > 2
        for: 5m
        labels:
          severity: medium
          category: performance
          consolidated: "true"
        annotations:
          summary: "High latency in cross-service communication"
          description: "95th percentile latency is {{ $value }}s"
          impact: "Slow response times affecting user experience"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/high-latency"

  # ==============================================================================
  # DATABASE LAYER CONSOLIDATION RULES
  # ==============================================================================

  - name: consolidated.database.health
    interval: 60s
    rules:
      # Database Connection Pool Health
      - alert: DatabaseConnectionPoolExhaustion
        expr: |
          (
            sum(pgbouncer_pools_client_active_connections) by (instance) /
            sum(pgbouncer_pools_maxwait_us) by (instance)
          ) > 0.8
        for: 3m
        labels:
          severity: high
          service: database
          category: resource-utilization
          consolidated: "true"
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "{{ $value }}% of database connections in use"
          impact: "New database connections may be refused"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/db-pool-exhaustion"

      # Vector Database Performance
      - alert: QdrantSlowQueries
        expr: |
          histogram_quantile(0.95, 
            rate(qdrant_request_duration_seconds_bucket[5m])
          ) > 1
        for: 5m
        labels:
          severity: medium
          service: qdrant
          category: performance
          consolidated: "true"
        annotations:
          summary: "Slow vector database queries detected"
          description: "95th percentile query time is {{ $value }}s"
          impact: "AI reasoning and search performance degraded"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/qdrant-slow-queries"

  # ==============================================================================
  # COST OPTIMIZATION TRACKING RULES
  # ==============================================================================

  - name: consolidated.cost.optimization
    interval: 300s  # 5 minute intervals for cost tracking
    rules:
      # Resource Cost Tracking (for $400K savings validation)
      - record: cost:cpu_hours_saved
        expr: |
          (
            # Previous 31-service CPU usage baseline (estimated)
            (31 * 0.5) - 
            # Current consolidated CPU usage
            sum(rate(container_cpu_usage_seconds_total{name=~".*aiwfe.*"}[1h]))
          ) * 24  # Convert to daily hours saved

      - record: cost:memory_gb_hours_saved
        expr: |
          (
            # Previous 31-service memory baseline (estimated 8GB per service)
            (31 * 8 * 1073741824) - 
            # Current consolidated memory usage in bytes
            sum(container_memory_usage_bytes{name=~".*aiwfe.*"})
          ) / 1073741824 * 24  # Convert to GB-hours saved per day

      # Cost Savings Achievement Alert
      - alert: CostOptimizationTargetAchieved
        expr: cost:cpu_hours_saved > 0 and cost:memory_gb_hours_saved > 0
        for: 1h
        labels:
          severity: info
          category: cost-optimization
          consolidated: "true"
        annotations:
          summary: "Cost optimization targets are being achieved"
          description: "CPU hours saved: {{ $value }}, Memory GB-hours saved: {{ $value }}"
          impact: "Positive progress toward $400K annual savings target"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/consolidated/cost-optimization-success"

  # ==============================================================================
  # PRODUCTION ENDPOINT HEALTH RULES
  # ==============================================================================

  - name: consolidated.production.health
    interval: 60s
    rules:
      # Production Site Availability
      - alert: ProductionSiteDown
        expr: probe_success{job="production-health", instance="https://aiwfe.com"} == 0
        for: 2m
        labels:
          severity: critical
          category: availability
          production: "true"
        annotations:
          summary: "Production website is down"
          description: "Main production site https://aiwfe.com is not accessible"
          impact: "Complete service outage for end users"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/production/site-down"

      # Production API Health
      - alert: ProductionAPIDown
        expr: probe_success{job="production-health", instance="https://aiwfe.com/api/health"} == 0
        for: 2m
        labels:
          severity: critical
          category: availability
          production: "true"
        annotations:
          summary: "Production API is down"
          description: "Production API health endpoint is not responding"
          impact: "API functionality unavailable for end users"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/production/api-down"

      # Production Site Response Time
      - alert: ProductionSiteSlowResponse
        expr: probe_duration_seconds{job="production-health"} > 5
        for: 5m
        labels:
          severity: medium
          category: performance
          production: "true"
        annotations:
          summary: "Production site slow response time"
          description: "Production site response time is {{ $value }}s"
          impact: "Poor user experience due to slow page loads"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/production/slow-response"