groups:
  # ==============================================================================
  # INFRASTRUCTURE PERFORMANCE AND AVAILABILITY RULES
  # ==============================================================================
  
  - name: infrastructure.container.rules
    interval: 30s
    rules:
      # Container CPU Usage
      - alert: HighContainerCPUUsage
        expr: (rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100) > 80
        for: 5m
        labels:
          severity: high
          category: resource-utilization
        annotations:
          summary: "High container CPU usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} CPU on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/high-cpu-usage"

      - alert: CriticalContainerCPUUsage
        expr: (rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100) > 95
        for: 2m
        labels:
          severity: critical
          category: resource-utilization
        annotations:
          summary: "Critical container CPU usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} CPU on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/critical-cpu-usage"

      # Container Memory Usage
      - alert: HighContainerMemoryUsage
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100) > 80
        for: 5m
        labels:
          severity: high
          category: resource-utilization
        annotations:
          summary: "High container memory usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of allocated memory on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/high-memory-usage"

      - alert: CriticalContainerMemoryUsage
        expr: (container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100) > 95
        for: 2m
        labels:
          severity: critical
          category: resource-utilization
        annotations:
          summary: "Critical container memory usage"
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of allocated memory on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/critical-memory-usage"

      # Container Restart Detection
      - alert: ContainerRestartLoop
        expr: increase(container_start_time_seconds{name!=""}[10m]) > 2
        for: 5m
        labels:
          severity: high
          category: stability
        annotations:
          summary: "Container restart loop detected"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last 10 minutes on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/container-restart-loop"

      # Container OOMKilled Detection
      - alert: ContainerOOMKilled
        expr: increase(container_memory_failures_total{type="oom_kill",name!=""}[5m]) > 0
        for: 0m
        labels:
          severity: critical
          category: resource-utilization
        annotations:
          summary: "Container killed by OOM"
          description: "Container {{ $labels.name }} was killed by OOM killer on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/infrastructure/container-oom-killed"

  # ==============================================================================
  # DATABASE INFRASTRUCTURE RULES
  # ==============================================================================

  - name: infrastructure.database.rules
    interval: 30s
    rules:
      # PostgreSQL Connection Usage
      - alert: HighPostgreSQLConnections
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) * 100 > 80
        for: 3m
        labels:
          severity: high
          service: postgresql
          category: resource-utilization
        annotations:
          summary: "High PostgreSQL connection usage"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of max connections on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/high-connections"

      - alert: CriticalPostgreSQLConnections
        expr: (pg_stat_database_numbackends / pg_settings_max_connections) * 100 > 95
        for: 1m
        labels:
          severity: critical
          service: postgresql
          category: resource-utilization
        annotations:
          summary: "Critical PostgreSQL connection usage"
          description: "PostgreSQL is using {{ $value | humanizePercentage }} of max connections on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/critical-connections"

      # PostgreSQL Slow Queries
      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_statements_mean_time_ms[5m]) > 1000
        for: 5m
        labels:
          severity: medium
          service: postgresql
          category: performance
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "Average query time is {{ $value }}ms on database {{ $labels.datname }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/slow-queries"

      # PostgreSQL Replication Lag (if applicable)
      - alert: PostgreSQLReplicationLag
        expr: pg_stat_replication_lag > 10
        for: 2m
        labels:
          severity: high
          service: postgresql
          category: replication
        annotations:
          summary: "PostgreSQL replication lag detected"
          description: "Replication lag is {{ $value }}s for replica {{ $labels.application_name }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/replication-lag"

      # PostgreSQL Database Size Growth
      - alert: RapidDatabaseGrowth
        expr: increase(pg_database_size_bytes[1h]) > (100 * 1024 * 1024 * 1024)  # 100GB growth in 1 hour
        for: 0m
        labels:
          severity: medium
          service: postgresql
          category: capacity
        annotations:
          summary: "Rapid database growth detected"
          description: "Database {{ $labels.datname }} grew by {{ $value }} bytes in the last hour on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/rapid-growth"

      # PgBouncer Pool Exhaustion
      - alert: PgBouncerPoolExhaustion
        expr: (pgbouncer_pools_client_active_connections / pgbouncer_pools_maxwait_us) > 0.9
        for: 3m
        labels:
          severity: high
          service: pgbouncer
          category: resource-utilization
        annotations:
          summary: "PgBouncer pool exhaustion"
          description: "PgBouncer pool {{ $labels.database }} is {{ $value | humanizePercentage }} exhausted on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/database/pgbouncer-exhaustion"

  # ==============================================================================
  # REDIS CACHE INFRASTRUCTURE RULES
  # ==============================================================================

  - name: infrastructure.redis.rules
    interval: 30s
    rules:
      # Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 80
        for: 5m
        labels:
          severity: high
          service: redis
          category: resource-utilization
        annotations:
          summary: "High Redis memory usage"
          description: "Redis is using {{ $value | humanizePercentage }} of allocated memory on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/redis/high-memory-usage"

      - alert: CriticalRedisMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: redis
          category: resource-utilization
        annotations:
          summary: "Critical Redis memory usage"
          description: "Redis is using {{ $value | humanizePercentage }} of allocated memory on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/redis/critical-memory-usage"

      # Redis Connection Issues
      - alert: HighRedisConnections
        expr: redis_connected_clients > (redis_config_maxclients * 0.8)
        for: 3m
        labels:
          severity: high
          service: redis
          category: resource-utilization
        annotations:
          summary: "High Redis connection count"
          description: "Redis has {{ $value }} connections (80% of max) on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/redis/high-connections"

      # Redis Keyspace Hit Rate
      - alert: LowRedisCacheHitRate
        expr: (rate(redis_keyspace_hits_total[5m]) / (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m]))) * 100 < 80
        for: 5m
        labels:
          severity: medium
          service: redis
          category: performance
        annotations:
          summary: "Low Redis cache hit rate"
          description: "Redis cache hit rate is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/redis/low-hit-rate"

      # Redis Evicted Keys
      - alert: RedisKeyEviction
        expr: increase(redis_evicted_keys_total[5m]) > 0
        for: 0m
        labels:
          severity: medium
          service: redis
          category: performance
        annotations:
          summary: "Redis key eviction detected"
          description: "Redis evicted {{ $value }} keys in the last 5 minutes on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/redis/key-eviction"

  # ==============================================================================
  # VECTOR DATABASE (QDRANT) INFRASTRUCTURE RULES
  # ==============================================================================

  - name: infrastructure.qdrant.rules
    interval: 60s
    rules:
      # Qdrant Service Availability
      - alert: QdrantServiceDown
        expr: up{job="qdrant"} == 0
        for: 2m
        labels:
          severity: critical
          service: qdrant
          category: availability
        annotations:
          summary: "Qdrant vector database is down"
          description: "Qdrant service {{ $labels.instance }} is not responding"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/qdrant/service-down"

      # Qdrant Collection Size Growth
      - alert: RapidQdrantCollectionGrowth
        expr: increase(qdrant_collections_vectors_count[1h]) > 100000
        for: 0m
        labels:
          severity: medium
          service: qdrant
          category: capacity
        annotations:
          summary: "Rapid Qdrant collection growth"
          description: "Collection {{ $labels.collection }} grew by {{ $value }} vectors in the last hour on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/qdrant/rapid-growth"

  # ==============================================================================
  # SYSTEM RESOURCE RULES (if node_exporter is added)
  # ==============================================================================

  - name: infrastructure.system.rules
    interval: 30s
    rules:
      # System CPU Usage
      - alert: HighSystemCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 85
        for: 5m
        labels:
          severity: high
          category: system-resources
        annotations:
          summary: "High system CPU usage"
          description: "System CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/system/high-cpu-usage"

      # System Memory Usage
      - alert: HighSystemMemoryUsage
        expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100 > 85
        for: 5m
        labels:
          severity: high
          category: system-resources
        annotations:
          summary: "High system memory usage"
          description: "System memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/system/high-memory-usage"

      # Disk Space Usage
      - alert: HighDiskSpaceUsage
        expr: ((node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 > 85
        for: 5m
        labels:
          severity: high
          category: system-resources
        annotations:
          summary: "High disk space usage"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.device }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/system/high-disk-usage"

      - alert: CriticalDiskSpaceUsage
        expr: ((node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 > 95
        for: 2m
        labels:
          severity: critical
          category: system-resources
        annotations:
          summary: "Critical disk space usage"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.device }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/system/critical-disk-usage"

      # High Disk I/O
      - alert: HighDiskIOUtilization
        expr: irate(node_disk_io_time_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: medium
          category: system-resources
        annotations:
          summary: "High disk I/O utilization"
          description: "Disk I/O utilization is {{ $value | humanizePercentage }} on {{ $labels.device }} on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/system/high-disk-io"

  # ==============================================================================
  # NETWORK AND CONNECTIVITY RULES
  # ==============================================================================

  - name: infrastructure.network.rules
    interval: 30s
    rules:
      # Network Interface Errors
      - alert: HighNetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) + rate(node_network_transmit_errs_total[5m]) > 10
        for: 5m
        labels:
          severity: medium
          category: network
        annotations:
          summary: "High network error rate"
          description: "Network interface {{ $labels.device }} has {{ $value }} errors/sec on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/network/high-errors"

      # Network Saturation
      - alert: HighNetworkBandwidthUsage
        expr: ((rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m])) * 8) > (100 * 1024 * 1024)  # 100 Mbps
        for: 10m
        labels:
          severity: medium
          category: network
        annotations:
          summary: "High network bandwidth usage"
          description: "Network interface {{ $labels.device }} is using {{ $value }} bytes/sec on {{ $labels.instance }}"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/network/high-bandwidth"