global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aiwfe-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - '/etc/prometheus/test_health_rules.yml'
  - '/etc/prometheus/cognitive_services_rules.yml'
  - '/etc/prometheus/authentication_rules.yml'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Worker Service - Currently not running
  # - job_name: 'worker'
  #   static_configs:
  #     - targets: ['worker:8001']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s

  # API Service - Main application metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Coordination Service - Health monitoring only (no metrics endpoint)
  # Monitoring via service-health job below

  # Hybrid Memory Service - Fixed content-type header
  - job_name: 'hybrid-memory-service'
    static_configs:
      - targets: ['hybrid-memory-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Learning Service - Health monitoring only (no metrics endpoint)
  # Monitoring via service-health job below

  # Perception Service - Health monitoring only (no metrics endpoint)  
  # Monitoring via service-health job below

  # Reasoning Service - Fixed content-type header
  - job_name: 'reasoning-service'
    static_configs:
      - targets: ['reasoning-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # GPU Monitor Service
  - job_name: 'gpu-monitor'
    static_configs:
      - targets: ['gpu-monitor:8025']
    metrics_path: '/metrics'
    scrape_interval: 45s
    scrape_timeout: 30s

  # Monitoring Aggregation Service - Service status metrics
  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:8020']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # PgBouncer Exporter
  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer_exporter:9127']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 30s

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Infrastructure Recovery Service - Not currently running
  # - job_name: 'infrastructure-recovery-service'
  #   static_configs:
  #     - targets: ['infrastructure-recovery-service:8010']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s

  # Health Monitor Service - Not currently running
  # - job_name: 'health-monitor'
  #   static_configs:
  #     - targets: ['health-monitor:8888']
  #   metrics_path: '/metrics'
  #   scrape_interval: 15s

  # Qdrant vector database - check if metrics endpoint exists
  # - job_name: 'qdrant'
  #   static_configs:
  #     - targets: ['qdrant:6333']
  #   metrics_path: '/metrics'
  #   scrape_interval: 30s

  # Ollama LLM service - check if metrics endpoint exists
  # - job_name: 'ollama'
  #   static_configs:
  #     - targets: ['ollama:11434']
  #   metrics_path: '/metrics'
  #   scrape_interval: 60s

  # Blackbox Exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://aiwfe.com
          - https://aiwfe.com/api/v1/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # Health endpoint monitoring for internal services
  - job_name: 'service-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api:8000/health
          - http://coordination-service:8001/health
          - http://hybrid-memory-service:8002/health
          - http://learning-service:8003/health
          - http://perception-service:8004/health
          - http://reasoning-service:8005/health
          - http://voice-interaction-service:8006/health
          - http://chat-service:8007/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # Infrastructure health monitoring (Redis, Postgres, etc.)
  - job_name: 'infrastructure-health'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - redis:6379
          - postgres:5432
          - qdrant:6333
          - ollama:11434
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # Docker Swarm monitoring (if applicable) - Disabled: Docker daemon metrics not configured
  # To enable: Add {"metrics-addr": "0.0.0.0:9323", "experimental": true} to /etc/docker/daemon.json
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['172.17.0.1:9323']
  #   scrape_interval: 30s
