groups:
  - name: security_authentication
    interval: 30s
    rules:
      # Authentication failure rate alerts
      - alert: HighAuthenticationFailureRate
        expr: rate(security_auth_failures_total[5m]) > 0.1
        for: 2m
        labels:
          severity: high
          category: authentication
          service: "{{ $labels.service }}"
        annotations:
          summary: "High authentication failure rate detected"
          description: "Authentication failure rate is {{ $value }} failures/second for service {{ $labels.service }} from IP {{ $labels.ip_address }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/auth-failures"

      - alert: CriticalAuthenticationFailureRate
        expr: rate(security_auth_failures_total[5m]) > 0.5
        for: 1m
        labels:
          severity: critical
          category: authentication
          service: "{{ $labels.service }}"
        annotations:
          summary: "Critical authentication failure rate - possible brute force attack"
          description: "Authentication failure rate is {{ $value }} failures/second for service {{ $labels.service }}. This may indicate a brute force attack."
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/brute-force-response"

      # JWT token operation failures
      - alert: JWTTokenFailures
        expr: rate(security_jwt_operations_total{status="failed"}[5m]) > 0.05
        for: 3m
        labels:
          severity: medium
          category: authentication
          token_type: "{{ $labels.token_type }}"
        annotations:
          summary: "JWT token operation failures detected"
          description: "JWT {{ $labels.operation }} operations are failing at {{ $value }} failures/second for {{ $labels.token_type }} tokens"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/jwt-failures"

  - name: security_authorization
    interval: 30s
    rules:
      # Authorization violation alerts
      - alert: AuthorizationViolations
        expr: rate(security_authz_violations_total[5m]) > 0.01
        for: 2m
        labels:
          severity: high
          category: authorization
          service: "{{ $labels.service }}"
          violation_type: "{{ $labels.violation_type }}"
        annotations:
          summary: "Authorization violations detected"
          description: "Authorization violations occurring at {{ $value }} violations/second for {{ $labels.violation_type }} in service {{ $labels.service }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/authz-violations"

      # Cross-service authentication failures
      - alert: CrossServiceAuthFailures
        expr: rate(security_cross_service_auth_total{status="failed"}[5m]) > 0.02
        for: 3m
        labels:
          severity: high
          category: authorization
          source_service: "{{ $labels.source_service }}"
          target_service: "{{ $labels.target_service }}"
        annotations:
          summary: "Cross-service authentication failures"
          description: "Cross-service auth failures between {{ $labels.source_service }} and {{ $labels.target_service }} at {{ $value }} failures/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/cross-service-auth"

  - name: security_violations
    interval: 30s
    rules:
      # General security violations
      - alert: SecurityViolations
        expr: rate(security_violations_total[5m]) > 0.01
        for: 2m
        labels:
          severity: "{{ $labels.severity }}"
          category: security_violation
          violation_type: "{{ $labels.violation_type }}"
          service: "{{ $labels.service }}"
        annotations:
          summary: "Security violations detected"
          description: "{{ $labels.violation_type }} violations in {{ $labels.service }} at {{ $value }} violations/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/violations"

      # Critical security violations
      - alert: CriticalSecurityViolations
        expr: rate(security_violations_total{severity="critical"}[5m]) > 0
        for: 0s
        labels:
          severity: critical
          category: security_violation
          violation_type: "{{ $labels.violation_type }}"
          service: "{{ $labels.service }}"
        annotations:
          summary: "Critical security violations detected"
          description: "Critical {{ $labels.violation_type }} violations detected in {{ $labels.service }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/critical-violations"

      # Security violation rate spike
      - alert: SecurityViolationSpike
        expr: rate(security_violation_rate_per_minute[5m]) > 10
        for: 1m
        labels:
          severity: high
          category: security_violation
        annotations:
          summary: "Security violation rate spike"
          description: "Security violations spiking to {{ $value }} violations/minute"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/violation-spike"

  - name: security_data_access
    interval: 60s
    rules:
      # Excessive data access
      - alert: ExcessiveDataAccess
        expr: rate(security_data_access_volume_total[10m]) > 1000
        for: 5m
        labels:
          severity: medium
          category: data_access
          service: "{{ $labels.service }}"
          table_name: "{{ $labels.table_name }}"
        annotations:
          summary: "Excessive data access detected"
          description: "High data access volume: {{ $value }} rows/second from {{ $labels.service }} on {{ $labels.table_name }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/data-access"

      # Sensitive data access spike
      - alert: SensitiveDataAccessSpike
        expr: rate(security_data_access_total{sensitive="true"}[5m]) > 10
        for: 3m
        labels:
          severity: high
          category: data_access
          service: "{{ $labels.service }}"
        annotations:
          summary: "Sensitive data access spike"
          description: "Sensitive data access spike: {{ $value }} accesses/second in {{ $labels.service }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/sensitive-data"

      # Slow data access (potential attack)
      - alert: SlowDataAccess
        expr: histogram_quantile(0.95, rate(security_data_access_response_time_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: medium
          category: data_access
          service: "{{ $labels.service }}"
        annotations:
          summary: "Slow data access detected"
          description: "95th percentile data access time is {{ $value }} seconds in {{ $labels.service }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/slow-access"

  - name: security_tool_execution
    interval: 30s
    rules:
      # Tool execution security failures
      - alert: ToolExecutionSecurityFailures
        expr: rate(security_tool_execution_total{status="failed"}[5m]) > 0.02
        for: 2m
        labels:
          severity: medium
          category: tool_execution
          tool_name: "{{ $labels.tool_name }}"
        annotations:
          summary: "Tool execution security failures"
          description: "Tool {{ $labels.tool_name }} security failures at {{ $value }} failures/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/tool-failures"

      # Sandbox violations
      - alert: SandboxViolations
        expr: rate(security_sandbox_violations_total[5m]) > 0
        for: 1m
        labels:
          severity: high
          category: tool_execution
          tool_name: "{{ $labels.tool_name }}"
          violation_type: "{{ $labels.violation_type }}"
        annotations:
          summary: "Sandbox violations detected"
          description: "{{ $labels.violation_type }} sandbox violations in {{ $labels.tool_name }} at {{ $value }} violations/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/sandbox-violations"

  - name: security_websocket
    interval: 30s
    rules:
      # WebSocket authentication failures
      - alert: WebSocketAuthFailures
        expr: rate(security_websocket_auth_failures_total[5m]) > 0.05
        for: 2m
        labels:
          severity: medium
          category: websocket
          failure_reason: "{{ $labels.failure_reason }}"
        annotations:
          summary: "WebSocket authentication failures"
          description: "WebSocket auth failures due to {{ $labels.failure_reason }} at {{ $value }} failures/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/websocket-auth"

      # High WebSocket connection failures
      - alert: WebSocketConnectionFailures
        expr: rate(security_websocket_connections_total{status="failed"}[5m]) > 0.1
        for: 3m
        labels:
          severity: medium
          category: websocket
        annotations:
          summary: "High WebSocket connection failure rate"
          description: "WebSocket connections failing at {{ $value }} failures/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/websocket-failures"

  - name: security_network
    interval: 30s
    rules:
      # High error rate from network requests
      - alert: HighNetworkErrorRate
        expr: rate(security_network_requests_total{status_code=~"4.*|5.*"}[5m]) / rate(security_network_requests_total[5m]) > 0.1
        for: 3m
        labels:
          severity: medium
          category: network
          service: "{{ $labels.service }}"
        annotations:
          summary: "High network error rate"
          description: "Network error rate is {{ $value | humanizePercentage }} for {{ $labels.service }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/network-errors"

      # SSL certificate issues
      - alert: SSLCertificateExpiring
        expr: security_ssl_certificate_status{security_ssl_certificate_status="expiring_soon"} == 1
        for: 0s
        labels:
          severity: high
          category: network
          service: "{{ $labels.service }}"
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.service }} is expiring soon"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/ssl-renewal"

      - alert: SSLCertificateExpired
        expr: security_ssl_certificate_status{security_ssl_certificate_status="expired"} == 1
        for: 0s
        labels:
          severity: critical
          category: network
          service: "{{ $labels.service }}"
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate for {{ $labels.service }} has expired"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/ssl-expired"

  - name: security_threats
    interval: 30s
    rules:
      # Threat detections
      - alert: ThreatDetected
        expr: rate(security_threat_detections_total[5m]) > 0
        for: 1m
        labels:
          severity: "{{ $labels.severity }}"
          category: threat_detection
          threat_type: "{{ $labels.threat_type }}"
          source: "{{ $labels.source }}"
        annotations:
          summary: "Security threat detected"
          description: "{{ $labels.threat_type }} threat detected by {{ $labels.source }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/threat-response"

      # High anomaly scores
      - alert: HighAnomalyScore
        expr: histogram_quantile(0.95, rate(security_anomaly_scores_bucket[10m])) > 0.8
        for: 5m
        labels:
          severity: medium
          category: threat_detection
          detection_type: "{{ $labels.detection_type }}"
        annotations:
          summary: "High security anomaly scores"
          description: "95th percentile anomaly score is {{ $value }} for {{ $labels.detection_type }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/anomalies"

      # Critical anomaly scores
      - alert: CriticalAnomalyScore
        expr: histogram_quantile(0.95, rate(security_anomaly_scores_bucket[5m])) > 0.95
        for: 2m
        labels:
          severity: high
          category: threat_detection
          detection_type: "{{ $labels.detection_type }}"
        annotations:
          summary: "Critical security anomaly scores"
          description: "Critical anomaly score detected: {{ $value }} for {{ $labels.detection_type }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/critical-anomalies"

  - name: security_rate_limiting
    interval: 30s
    rules:
      # Rate limit violations
      - alert: RateLimitViolations
        expr: rate(security_rate_limit_violations_total[5m]) > 0.1
        for: 2m
        labels:
          severity: medium
          category: rate_limiting
          endpoint: "{{ $labels.endpoint }}"
        annotations:
          summary: "Rate limit violations detected"
          description: "Rate limit violations on {{ $labels.endpoint }} at {{ $value }} violations/second"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/rate-limits"

      # Excessive rate limit violations from single IP
      - alert: ExcessiveRateLimitViolations
        expr: rate(security_rate_limit_violations_total[5m]) > 1.0
        for: 1m
        labels:
          severity: high
          category: rate_limiting
          endpoint: "{{ $labels.endpoint }}"
          ip_address: "{{ $labels.ip_address }}"
        annotations:
          summary: "Excessive rate limit violations"
          description: "Excessive rate limit violations from {{ $labels.ip_address }} on {{ $labels.endpoint }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/rate-limit-blocking"

  - name: security_system_health
    interval: 60s
    rules:
      # Security health score
      - alert: LowSecurityHealthScore
        expr: security_health_score < 70
        for: 5m
        labels:
          severity: medium
          category: system_health
        annotations:
          summary: "Low security health score"
          description: "Security health score has dropped to {{ $value }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/health-score"

      - alert: CriticalSecurityHealthScore
        expr: security_health_score < 50
        for: 2m
        labels:
          severity: critical
          category: system_health
        annotations:
          summary: "Critical security health score"
          description: "Security health score is critically low at {{ $value }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/critical-health"

      # Security monitoring status
      - alert: SecurityMonitoringDegraded
        expr: security_monitoring_status{security_monitoring_status="degraded"} == 1
        for: 3m
        labels:
          severity: medium
          category: system_health
        annotations:
          summary: "Security monitoring degraded"
          description: "Security monitoring system is operating in degraded mode"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/monitoring-degraded"

      - alert: SecurityMonitoringCritical
        expr: security_monitoring_status{security_monitoring_status="critical"} == 1
        for: 1m
        labels:
          severity: high
          category: system_health
        annotations:
          summary: "Security monitoring critical"
          description: "Security monitoring system is in critical state"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/monitoring-critical"

      - alert: SecurityMonitoringOffline
        expr: security_monitoring_status{security_monitoring_status="offline"} == 1
        for: 0s
        labels:
          severity: critical
          category: system_health
        annotations:
          summary: "Security monitoring offline"
          description: "Security monitoring system is offline"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/monitoring-offline"

      # Database security
      - alert: ExcessiveDatabaseConnections
        expr: security_database_connections_active > 100
        for: 5m
        labels:
          severity: medium
          category: database
        annotations:
          summary: "Excessive database connections"
          description: "{{ $value }} active database connections with security context"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/database-connections"

      # High concurrent sessions
      - alert: HighConcurrentSessions
        expr: security_concurrent_sessions > 200
        for: 3m
        labels:
          severity: medium
          category: sessions
          user_type: "{{ $labels.user_type }}"
        annotations:
          summary: "High concurrent user sessions"
          description: "{{ $value }} concurrent sessions for {{ $labels.user_type }} users"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/concurrent-sessions"

  - name: security_audit
    interval: 60s
    rules:
      # Audit log creation issues
      - alert: AuditLogCreationRate
        expr: rate(security_audit_log_entries_total[10m]) > 100
        for: 5m
        labels:
          severity: medium
          category: audit
          operation: "{{ $labels.operation }}"
        annotations:
          summary: "High audit log creation rate"
          description: "Audit logs being created at {{ $value }} entries/second for {{ $labels.operation }}"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/audit-logs"

      # Missing audit logs (potential tampering)
      - alert: AuditLogGap
        expr: absent_over_time(security_audit_log_entries_total[10m])
        for: 5m
        labels:
          severity: high
          category: audit
        annotations:
          summary: "Audit log creation gap detected"
          description: "No audit logs have been created in the last 10 minutes"
          runbook_url: "https://runbooks.ai-workflow-engine.local/security/audit-gap"