groups:
  # ==============================================================================
  # SSL CERTIFICATE MONITORING RULES
  # ==============================================================================
  
  - name: ssl.certificate.monitoring
    interval: 300s  # Check every 5 minutes
    rules:
      # SSL Certificate Expiration Warning (30 days)
      - alert: SSLCertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry{job="ssl-certificate-monitoring"} - time() < 86400 * 30
        for: 0m
        labels:
          severity: medium
          category: security
          certificate: "production"
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ ($value - time()) / 86400 | humanizeDuration }}"
          impact: "Certificate will expire soon, renewal required"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-renewal"

      # SSL Certificate Expiration Critical (7 days)
      - alert: SSLCertificateExpiringCritical
        expr: probe_ssl_earliest_cert_expiry{job="ssl-certificate-monitoring"} - time() < 86400 * 7
        for: 0m
        labels:
          severity: critical
          category: security
          certificate: "production"
        annotations:
          summary: "SSL certificate expiring in less than 7 days"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ ($value - time()) / 86400 | humanizeDuration }}"
          impact: "URGENT: Certificate expires very soon, immediate renewal required"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-urgent-renewal"

      # SSL Certificate Already Expired
      - alert: SSLCertificateExpired
        expr: probe_ssl_earliest_cert_expiry{job="ssl-certificate-monitoring"} - time() <= 0
        for: 0m
        labels:
          severity: critical
          category: security
          certificate: "production"
        annotations:
          summary: "SSL certificate has expired"
          description: "SSL certificate for {{ $labels.instance }} has already expired"
          impact: "CRITICAL: Site not accessible via HTTPS, users will see security warnings"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-expired"

      # SSL Certificate Chain Issues
      - alert: SSLCertificateChainInvalid
        expr: probe_ssl_chain_valid{job="ssl-certificate-monitoring"} == 0
        for: 1m
        labels:
          severity: high
          category: security
          certificate: "production"
        annotations:
          summary: "SSL certificate chain is invalid"
          description: "SSL certificate chain for {{ $labels.instance }} is not valid"
          impact: "Users may see certificate warnings, trust issues"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-chain-invalid"

      # SSL Certificate Subject Mismatch
      - alert: SSLCertificateSubjectMismatch
        expr: probe_ssl_subject_matches{job="ssl-certificate-monitoring"} == 0
        for: 1m
        labels:
          severity: high
          category: security
          certificate: "production"
        annotations:
          summary: "SSL certificate subject mismatch"
          description: "SSL certificate subject does not match {{ $labels.instance }}"
          impact: "Certificate name mismatch, users will see security warnings"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-subject-mismatch"

  # ==============================================================================
  # SSL/TLS SECURITY MONITORING
  # ==============================================================================

  - name: ssl.security.monitoring
    interval: 300s
    rules:
      # Weak SSL/TLS Version Detection
      - alert: WeakTLSVersion
        expr: probe_tls_version_info{job="ssl-certificate-monitoring", version!~"TLS 1\\.[23]"} == 1
        for: 5m
        labels:
          severity: high
          category: security
          tls: "version"
        annotations:
          summary: "Weak TLS version in use"
          description: "{{ $labels.instance }} is using TLS version {{ $labels.version }}"
          impact: "Security vulnerability, outdated TLS version in use"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/weak-tls-version"

      # SSL Certificate Key Size Check
      - alert: WeakSSLKeySize
        expr: probe_ssl_key_bits{job="ssl-certificate-monitoring"} < 2048
        for: 1m
        labels:
          severity: high
          category: security
          certificate: "key-strength"
        annotations:
          summary: "Weak SSL certificate key size"
          description: "SSL certificate for {{ $labels.instance }} uses {{ $value }}-bit key"
          impact: "Weak encryption, security vulnerability"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/weak-key-size"

  # ==============================================================================
  # CERTIFICATE LIFECYCLE MANAGEMENT
  # ==============================================================================

  - name: ssl.lifecycle.management
    interval: 600s  # Check every 10 minutes
    rules:
      # Certificate Validation Success Rate
      - record: ssl:validation_success_rate
        expr: |
          (
            sum(probe_success{job="ssl-certificate-monitoring"}) /
            count(probe_success{job="ssl-certificate-monitoring"})
          ) * 100

      # Certificate Health Score
      - record: ssl:health_score
        expr: |
          (
            # Base score for valid certificates
            probe_success{job="ssl-certificate-monitoring"} * 40 +
            # Bonus for valid chain
            probe_ssl_chain_valid{job="ssl-certificate-monitoring"} * 20 +
            # Bonus for subject match
            probe_ssl_subject_matches{job="ssl-certificate-monitoring"} * 20 +
            # Bonus for time until expiry (scaled)
            (
              clamp_max(
                (probe_ssl_earliest_cert_expiry{job="ssl-certificate-monitoring"} - time()) / (86400 * 90),
                1
              ) * 20
            )
          )

      # Certificate Health Alert
      - alert: SSLCertificateHealthDegraded
        expr: ssl:health_score < 80
        for: 5m
        labels:
          severity: medium
          category: security
          certificate: "health"
        annotations:
          summary: "SSL certificate health degraded"
          description: "SSL certificate health score for {{ $labels.instance }} is {{ $value }}%"
          impact: "Certificate issues may affect site security and availability"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/certificate-health-degraded"

  # ==============================================================================
  # CERTIFICATE RENEWAL AUTOMATION ALERTS
  # ==============================================================================

  - name: ssl.renewal.automation
    interval: 3600s  # Check every hour
    rules:
      # Certificate Renewal Process Monitoring
      - alert: CertificateRenewalRequired
        expr: probe_ssl_earliest_cert_expiry{job="ssl-certificate-monitoring"} - time() < 86400 * 30
        for: 1h
        labels:
          severity: info
          category: maintenance
          certificate: "renewal"
        annotations:
          summary: "Certificate renewal process should start"
          description: "Certificate for {{ $labels.instance }} should begin renewal process"
          impact: "Proactive renewal required to prevent service disruption"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/start-renewal-process"

      # Certificate Monitoring Service Health
      - alert: CertificateMonitoringDown
        expr: up{job="ssl-certificate-monitoring"} == 0
        for: 10m
        labels:
          severity: high
          category: monitoring
          certificate: "monitoring"
        annotations:
          summary: "SSL certificate monitoring is down"
          description: "Cannot monitor SSL certificate status"
          impact: "No visibility into certificate expiration or health"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/monitoring-down"

  # ==============================================================================
  # PRODUCTION CERTIFICATE SPECIFIC RULES
  # ==============================================================================

  - name: ssl.production.specific
    interval: 300s
    rules:
      # AIWFE.com Specific Certificate Monitoring
      - alert: AIWFECertificateIssue
        expr: |
          probe_success{job="ssl-certificate-monitoring", instance="aiwfe.com:443"} == 0 or
          ssl:health_score{instance="aiwfe.com:443"} < 90
        for: 2m
        labels:
          severity: critical
          category: security
          domain: "aiwfe.com"
          production: "true"
        annotations:
          summary: "Critical issue with aiwfe.com SSL certificate"
          description: "Production domain aiwfe.com has SSL certificate issues"
          impact: "Main production site security compromised"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/aiwfe-certificate-issue"

      # Production Certificate Performance
      - alert: ProductionCertificateSlowValidation
        expr: probe_duration_seconds{job="ssl-certificate-monitoring", instance="aiwfe.com:443"} > 5
        for: 5m
        labels:
          severity: medium
          category: performance
          domain: "aiwfe.com"
          production: "true"
        annotations:
          summary: "Slow SSL certificate validation for production domain"
          description: "SSL handshake for aiwfe.com taking {{ $value }}s"
          impact: "Slow HTTPS connection establishment affecting user experience"
          runbook_url: "https://docs.ai-workflow-engine.local/runbooks/ssl/slow-validation"