groups:
  - name: health_monitoring
    interval: 30s
    rules:
      - alert: ServiceHealthFailure
        expr: probe_success{job="service-health"} == 0
        for: 1m
        labels:
          severity: high
          component: service
        annotations:
          summary: "Service health check failed for {{ $labels.instance }}"
          description: "Health check for {{ $labels.instance }} has been failing for 1 minute"