# Unified Orchestration Configuration
# Master configuration for the 12-Phase Agentic Orchestration Flow

version: "2.0"
name: "unified-workflow-orchestration"

# Project Structure
project:
  root_directory: "/home/marku/ai_workflow_engine/UnifiedWorkflow"
  working_directory: "/home/marku/ai_workflow_engine/UnifiedWorkflow"
  claude_config_directory: "/home/marku/ai_workflow_engine/UnifiedWorkflow/.claude"

# Phase Configuration
phases:
  phase_0:
    name: "Todo Context Integration"
    primary_agent: "orchestration-todo-manager"
    config_file: ".claude/orchestration_todos.json"
    description: "Cross-session todo management and context continuity"
    
  phase_1:
    name: "Agent Ecosystem Validation"
    primary_agent: "agent-integration-orchestrator"
    pre_execution_steps:
      - name: "git_environment_sync"
        description: "Pull latest workflow updates and improvements"
        protocol: "workflows/phase1-git-sync-protocol.yaml"
        mandatory: true
        timeout: 30000
    description: "Git synchronization and agent ecosystem validation"
    
  phase_2:
    name: "Strategic Intelligence Planning"
    primary_agents: ["project-orchestrator", "enhanced-nexus-synthesis"]
    description: "Strategic planning and historical pattern analysis"

# MCP Server Configuration  
mcp_servers:
  memory:
    config_file: "mcps/memory/mcp-memory-config.json"
    storage_path: "./.mcp/memory.db"
    max_entity_size: 8000
    
  redis:
    config_file: "mcps/redis/mcp-redis-config.json"
    connection: "localhost:6379"
    
  orchestration:
    config_file: "mcps/orchestration/mcp-orchestration-config.json"
    storage_path: "./.mcp/orchestration.db"
    
  playwright:
    config_file: "mcps/playwright/mcp-playwright-config.json"
    screenshot_path: "./.playwright-mcp/"

# ML Enhancement
ml_enhancement:
  enabled: true
  components:
    - "ml_enhanced_coordinator"
    - "predictive_ai_orchestrator"
  
# File Organization
file_organization:
  root_directory_max_files: 15
  reports_directory: "docs/reports/"
  evidence_directory: "docs/evidence/"