google_calendar_sync:
  # Configurable parameters for Google Calendar integration
  default_calendar: 'primary'
  sync_interval_minutes: 30
  max_events_per_sync: 50
  
  # OAuth 2.0 Configuration
  oauth:
    token_path: '~/.config/ai_workflow_engine/google_calendar_token.json'
    credentials_path: '~/.config/ai_workflow_engine/google_calendar_credentials.json'
    
  # Workflow-specific event tags
  event_tags:
    - 'ai_workflow'
    - 'automation'
    - 'scheduled_task'
  
  # Rate limiting and quota management
  rate_limits:
    requests_per_minute: 10
    max_concurrent_requests: 3