global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'production-alerts'
  
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 5m
    
    - match:
        severity: high
      receiver: 'high-priority-alerts'
      group_wait: 30s
      repeat_interval: 15m
    
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 1m
      repeat_interval: 30m

receivers:
  - name: 'production-alerts'
    webhook_configs:
      - url: 'http://api:8000/api/v1/alerts/webhook'
        send_resolved: true
  
  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://api:8000/api/v1/alerts/critical'
        send_resolved: true
  
  - name: 'high-priority-alerts'
    webhook_configs:
      - url: 'http://api:8000/api/v1/alerts/high'
        send_resolved: true
  
  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://api:8000/api/v1/alerts/warning'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
