global:
  # Global notification configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@aiwfe.com'
  smtp_auth_username: 'alerts@aiwfe.com'
  smtp_auth_password_file: '/run/secrets/smtp_password'
  smtp_require_tls: true
  
  # Slack integration for real-time notifications
  slack_api_url_file: '/run/secrets/slack_webhook_url'

# Route configuration optimized for consolidated 8-service architecture
route:
  group_by: ['alertname', 'severity', 'consolidated']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'consolidated-ops-team'
  
  routes:
    # === CRITICAL PRODUCTION ALERTS ===
    - match:
        severity: critical
        production: "true"
      receiver: 'production-critical'
      group_wait: 10s
      repeat_interval: 5m
      
    # === CONSOLIDATION SPECIFIC ALERTS ===
    - match:
        consolidated: "true"
      receiver: 'consolidation-monitoring'
      group_wait: 30s
      repeat_interval: 30m
      
    # === COST OPTIMIZATION ALERTS ===
    - match_re:
        category: '.*cost.*|.*efficiency.*'
      receiver: 'cost-optimization-team'
      group_wait: 60s
      repeat_interval: 4h
      
    # === WEBSOCKET PERFORMANCE ALERTS ===
    - match:
        protocol: "websocket"
      receiver: 'performance-team'
      group_wait: 30s
      repeat_interval: 15m
      
    # === SSL CERTIFICATE ALERTS ===
    - match:
        category: security
        certificate: "production"
      receiver: 'security-ssl-team'
      group_wait: 60s
      repeat_interval: 6h
      
    # === SERVICE AVAILABILITY ALERTS ===
    - match:
        category: availability
      receiver: 'availability-team'
      group_wait: 20s
      repeat_interval: 10m
      
    # === PERFORMANCE ALERTS ===
    - match:
        category: performance
      receiver: 'performance-team'
      group_wait: 2m
      repeat_interval: 30m
      
    # === RESOURCE UTILIZATION ALERTS ===
    - match:
        category: resource-utilization
      receiver: 'infrastructure-team'
      group_wait: 5m
      repeat_interval: 1h
      
    # === BUSINESS/SUCCESS ALERTS (INFO LEVEL) ===
    - match:
        severity: info
      receiver: 'business-metrics-team'
      group_wait: 10m
      repeat_interval: 24h

# Intelligent inhibition rules for noise reduction
inhibit_rules:
  # Suppress lower severity alerts when critical alerts are firing for same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'high'
    equal: ['service', 'instance']
    
  - source_match:
      severity: 'high'
    target_match:
      severity: 'medium'
    equal: ['service', 'instance']
    
  # Suppress individual service alerts when consolidated alert is firing
  - source_match:
      alertname: 'ConsolidationResourceOverutilization'
    target_match_re:
      alertname: '.*ResourceUtilization.*'
    equal: ['instance']
    
  # Suppress component alerts when main production site is down
  - source_match:
      alertname: 'ProductionSiteDown'
    target_match_re:
      alertname: '.*Service.*|.*API.*'
    equal: ['instance']
    
  # Suppress performance alerts during known maintenance
  - source_match:
      alertname: 'MaintenanceMode'
    target_match:
      category: 'performance'
    equal: ['instance']

# Receiver configurations for consolidated monitoring
receivers:
  # === DEFAULT CONSOLIDATED OPS TEAM ===
  - name: 'consolidated-ops-team'
    email_configs:
      - to: 'ops-team@aiwfe.com'
        headers:
          subject: '[AIWFE] {{ .GroupLabels.alertname }} - {{ .GroupLabels.severity }}'
        text: |
          AIWFE Consolidated Services Alert
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Category: {{ .Labels.category }}
          Instance: {{ .Labels.instance }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          {{ if .Annotations.impact }}Impact: {{ .Annotations.impact }}{{ end }}
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
    
    slack_configs:
      - channel: '#aiwfe-alerts'
        title: 'AIWFE Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Severity: {{ .Labels.severity | upper }}
          {{ if .Annotations.impact }}Impact: {{ .Annotations.impact }}{{ end }}
          {{ end }}

  # === CRITICAL PRODUCTION ALERTS ===
  - name: 'production-critical'
    email_configs:
      - to: 'ops-team@aiwfe.com,oncall@aiwfe.com,management@aiwfe.com'
        headers:
          subject: '🚨 CRITICAL: Production AIWFE.com Issue - {{ .GroupLabels.alertname }}'
        text: |
          CRITICAL PRODUCTION INCIDENT - IMMEDIATE ATTENTION REQUIRED
          
          Production website aiwfe.com is experiencing a critical issue requiring immediate intervention.
          
          {{ range .Alerts }}
          CRITICAL ALERT: {{ .Annotations.summary }}
          DESCRIPTION: {{ .Annotations.description }}
          SEVERITY: CRITICAL
          IMPACT: {{ .Annotations.impact }}
          SERVICE: {{ .Labels.service }}
          DOMAIN: {{ .Labels.domain }}
          STARTED: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          IMMEDIATE ACTIONS REQUIRED:
          1. Verify production site accessibility at https://aiwfe.com
          2. Check consolidated service health status
          3. Review recent deployment or configuration changes
          4. Activate incident response procedures
          
          {{ if .Annotations.runbook_url }}RUNBOOK: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
          
          This alert will repeat every 5 minutes until resolved.
    
    slack_configs:
      - channel: '#aiwfe-critical'
        title: '🚨 CRITICAL PRODUCTION ALERT'
        text: |
          <!channel> CRITICAL: Production aiwfe.com incident
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Impact: {{ .Annotations.impact }}
          {{ end }}
        color: 'danger'
    
    webhook_configs:
      - url: 'http://api:8000/api/v1/alerts/critical'
        send_resolved: true

  # === CONSOLIDATION MONITORING TEAM ===
  - name: 'consolidation-monitoring'
    email_configs:
      - to: 'architecture-team@aiwfe.com'
        headers:
          subject: '[CONSOLIDATION] {{ .GroupLabels.alertname }} - Service Architecture Alert'
        text: |
          CONSOLIDATION MONITORING ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Category: {{ .Labels.category }}
          Consolidation Impact: {{ .Annotations.impact }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Consolidated Service Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Consolidation Actions:
          1. Review service consolidation health and efficiency
          2. Check resource utilization targets (70-80%)
          3. Verify inter-service communication performance
          4. Monitor cost optimization progress
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # === COST OPTIMIZATION TEAM ===
  - name: 'cost-optimization-team'
    email_configs:
      - to: 'cost-team@aiwfe.com,architecture-team@aiwfe.com'
        headers:
          subject: '[COST] {{ .GroupLabels.alertname }} - $400K Savings Target Alert'
        text: |
          COST OPTIMIZATION ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Cost Impact: {{ .Annotations.impact }}
          Target: $400K Annual Savings
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Cost Optimization Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Recommended Actions:
          1. Review resource efficiency metrics (CPU/Memory utilization)
          2. Analyze cost savings projection trends
          3. Consider further consolidation opportunities
          4. Verify baseline cost calculations accuracy
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
    
    slack_configs:
      - channel: '#cost-optimization'
        title: 'Cost Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Progress toward $400K target may be affected
          {{ end }}

  # === WEBSOCKET PERFORMANCE TEAM ===
  - name: 'performance-team'
    email_configs:
      - to: 'performance-team@aiwfe.com'
        headers:
          subject: '[PERFORMANCE] {{ .GroupLabels.alertname }} - WebSocket Performance Alert'
        text: |
          WEBSOCKET PERFORMANCE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Performance Target: {{ .Labels.target }}
          Protocol: {{ .Labels.protocol }}
          Performance Impact: {{ .Annotations.impact }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Performance Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Performance Actions:
          1. Check WebSocket connection times (<30s target)
          2. Review network latency and backend performance
          3. Analyze real-time feature usage patterns
          4. Consider scaling or optimization improvements
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # === SSL SECURITY TEAM ===
  - name: 'security-ssl-team'
    email_configs:
      - to: 'security-team@aiwfe.com'
        headers:
          subject: '[SSL] {{ .GroupLabels.alertname }} - Certificate Security Alert'
        text: |
          SSL CERTIFICATE SECURITY ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Domain: {{ .Labels.domain }}
          Certificate Type: {{ .Labels.certificate }}
          Security Impact: {{ .Annotations.impact }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          SSL Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          SSL Actions:
          1. Check certificate expiration dates
          2. Verify certificate chain validity
          3. Test HTTPS accessibility for production domain
          4. Plan certificate renewal if needed
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # === SERVICE AVAILABILITY TEAM ===
  - name: 'availability-team'
    email_configs:
      - to: 'ops-team@aiwfe.com,oncall@aiwfe.com'
        headers:
          subject: '[AVAILABILITY] {{ .GroupLabels.alertname }} - Service Down Alert'
        text: |
          SERVICE AVAILABILITY ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Availability Impact: {{ .Annotations.impact }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Service Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Availability Actions:
          1. Check service health endpoints and status
          2. Review recent deployments or configuration changes
          3. Verify Kubernetes pod status and resource availability
          4. Test service connectivity and dependencies
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
    
    slack_configs:
      - channel: '#service-availability'
        title: 'Service Down: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          🔴 *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          {{ end }}
        color: 'warning'

  # === INFRASTRUCTURE TEAM ===
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure-team@aiwfe.com'
        headers:
          subject: '[INFRA] {{ .GroupLabels.alertname }} - Resource Alert'
        text: |
          INFRASTRUCTURE RESOURCE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Resource Type: {{ .Labels.category }}
          Infrastructure Impact: {{ .Annotations.impact }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Resource Details:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          Infrastructure Actions:
          1. Review resource utilization metrics
          2. Check for resource bottlenecks or exhaustion
          3. Consider scaling or resource optimization
          4. Monitor consolidation efficiency targets
          
          {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}

  # === BUSINESS METRICS TEAM ===
  - name: 'business-metrics-team'
    email_configs:
      - to: 'business-team@aiwfe.com'
        headers:
          subject: '[SUCCESS] {{ .GroupLabels.alertname }} - Achievement Alert'
        text: |
          BUSINESS SUCCESS ALERT
          
          {{ range .Alerts }}
          Achievement: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Business Impact: {{ .Annotations.impact }}
          Achievement Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          Success Metrics:
          {{ range .Labels.SortedPairs }}  {{ .Name }}: {{ .Value }}
          {{ end }}
          
          {{ if .Annotations.runbook_url }}Reference: {{ .Annotations.runbook_url }}{{ end }}
          {{ end }}
    
    slack_configs:
      - channel: '#business-metrics'
        title: '✅ Achievement: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          🎉 *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}
        color: 'good'

# Message templates for consistent formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'